#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-io
source io

# ##  curl::toFile
#
# This function is a wrapper around curl.
# It allows you to check the http status code and return 1 if it is not acceptable.
# It io::invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o ${2}.
#
# - $1: **fail** _as bool_:
#       true/false to indicate if the function should fail in case the execution fails
# - $2: **acceptable codes** _as string_:
#       list of http status codes that are acceptable, comma separated
#       (defaults to 200,201,202,204,301,304,308 if left empty)
# - $3: **path** _as string_:
#       the file in which to save the output of curl
# - $@: **curl arguments** _as any_:
#       options for curl
#
# Returns:
#
# - $?:
#   - 0 if the http status code is acceptable
#   - 1 otherwise
# - `RETURNED_VALUE`: the content of stderr
# - `RETURNED_VALUE2`: the http status code
#
# ```bash
# curl::toFile "true" "200,201" "/filePath" "https://example.com" || core::fail "The curl command failed."
# ```
function curl::toFile() {
  local failIfFails acceptableStatusCodes outputFile url
  failIfFails="${1:-false}"
  acceptableStatusCodes="${2:-200,201,202,204,301,304,308}"
  outputFile="${3}"
  shift 3

  # call curl
  local -i exitCode=0
  local httpStatusCode errors
  io::invoke5 "false" "0" "false" "" "curl" "--silent" "--show-error" "--location" "--write-out" "%{response_code}" "--output" "${outputFile}" "$@" || exitCode=$?
  httpStatusCode="${RETURNED_VALUE}"
  errors="${RETURNED_VALUE2}"

  # workaround in case of unknown args in curl
  # and for a bug in curl https://github.com/Homebrew/homebrew-core/issues/173294
  if [[ ${exitCode} != "0" && (${errors} == *"bad argument"* || ${errors} == *"is unknown"*) ]]; then
    log::debug "Trying to use curl without the many options."
    io::invoke5 "false" "0" "false" "" "curl" "--location" "-v" "--output" "${outputFile}" "$@" || exitCode=$?
    if [[ ${RETURNED_VALUE}${RETURNED_VALUE2} =~ "< HTTP/"([0-9.]+)" "([0-9]+)" " ]]; then
      httpStatusCode="${BASH_REMATCH[2]}"
    else
      httpStatusCode="??? Could not read from verbose curl output."
    fi
    errors="${RETURNED_VALUE2}"
  fi

  local url="$*"
  url="http${url##*http}"
  url="${url%% *}"
  url="${url%% \'}"

  log::debug "The curl command for url ⌜${url}⌝ ended with exit code ⌜${exitCode}⌝, the http return code was ⌜${httpStatusCode}⌝."

  # if the error code is acceptable, then we set it to 0
  if [[ ,${acceptableStatusCodes}, == *",${httpStatusCode},"* ]]; then
    exitCode=0
    log::debug "The http return code ⌜${httpStatusCode}⌝ is acceptable and exit code has been reset to 0 from ⌜${exitCode}⌝."
  else
    exitCode=1
    if log::isDebugEnabled || [[ ${failIfFails} == "true" ]]; then
      log::errorTrace "Curl error output stream:"
      log::printFileString "${errors}"
    fi
    local message="The http return code ⌜${httpStatusCode}⌝ is not acceptable for url ⌜${url}⌝."
    if [[ ${failIfFails} == "true" ]]; then
      core::fail "${message}"
    fi
    log::debug "${message}"
  fi

  RETURNED_VALUE="${errors}"
  RETURNED_VALUE2="${httpStatusCode}"
  return ${exitCode}
}

# ## curl::toVar
#
# This function is a wrapper around curl.
# It allows you to check the http status code and return 1 if it is not acceptable.
# It io::invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o "tempfile".
#
# - $1: **fail** _as bool_:
#       true/false to indicate if the function should fail in case the execution fails
# - $2: **acceptable codes** _as string_:
#       list of http status codes that are acceptable, comma separated
#       (defaults to 200,201,202,204,301,304,308 if left empty)
# - $@: **curl arguments** _as any_:
#       options for curl
#
# Returns:
#
# - $?:
#   - 0 if the http status code is acceptable
#   - 1 otherwise
# - `RETURNED_VALUE`: the content of the request
# - `RETURNED_VALUE2`: the content of stderr
# - `RETURNED_VALUE3`: the http status code
#
# ```bash
# curl::toVar false 200,201 https://example.com || core::fail "The curl command failed."
# ```
function curl::toVar() {
  local acceptableStatusCodes
  failIfFails="${1:-false}"
  acceptableStatusCodes="${2:-}"
  shift 2

  # reset the temporary file, only if needed
  if [[ -s "${GLOBAL_TEMPORARY_WORK_FILE}" ]]; then : >"${GLOBAL_TEMPORARY_WORK_FILE}"; fi

  local -i exitCode=0
  local errors httpStatusCode
  curl::toFile "${failIfFails}" "${acceptableStatusCodes}" "${GLOBAL_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
  errors="${RETURNED_VALUE}"
  httpStatusCode="${RETURNED_VALUE2}"

  io::readFile "${GLOBAL_TEMPORARY_WORK_FILE}"
  RETURNED_VALUE2="${errors}"
  RETURNED_VALUE3="${httpStatusCode}"
  return ${exitCode}
}
