#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# ## extension2::doNothing
#
# Does nothing
#
# ```bash
# extension2::doNothing
# ```
function extension2::doNothing() {
  log::info "Do nothing..."
}
