#!/usr/bin/env bash
set -Eeu -o pipefail

# This script is executed in a Docker container

function main() {
  export GLOBAL_MOCK_EPOCHSECONDS=548902800
  export VALET_CONFIG_LOG_PATTERN="<level>{-8s} <message>"
  export VALET_CONFIG_LOG_COLUMNS=9999
  export VALET_CONFIG_LOG_DISABLE_WRAP=true
  export VALET_CONFIG_LOG_DISABLE_HIGHLIGHT=true
  export VALET_CONFIG_ENABLE_COLORS=false

  echo "================================================"
  echo "valet install"
  echo "================================================"

  /home/me/install.sh --from-branch main --unattended

  echo
  echo "================================================"
  local before
  before="$(cat /home/me/.local/lib/valet/version)"
  printf '%s' "0.1.0" >~/.local/lib/valet/version
  if [[ -z ${before} ]]; then
    echo "Failed to read the current version, exiting test with error."
    exit 1
  fi
  cp /home/me/self-update.sh /home/me/.local/lib/valet/commands.d/self-update.sh

  echo
  echo "================================================"
  echo "valet self update --unattended"
  echo "================================================"

  export VALET_FROM_BRANCH=main
  export VALET_SKIP_SETUP=true
  export VALET_TEST_OVERRIDE_LATEST_VERSION=main
  /home/me/.local/lib/valet/valet self update --unattended
  local after
  after="$(cat /home/me/.local/lib/valet/version)"
  if [[ -z ${after} || ${after} == "0.1.0" ]]; then
    echo "Failed to read the updated version, exiting test with error."
    exit 1
  fi
}

main

echo "Self setup tests passed."
