#!/usr/bin/env bash
# author: github.com/jcaillon
# description: this script is a valet command

# shellcheck source=../libraries.d/lib-exe
source exe
# shellcheck source=../libraries.d/lib-fs
source fs
# shellcheck source=../libraries.d/lib-string
source string
# shellcheck source=../libraries.d/lib-interactive
source interactive
# shellcheck source=../libraries.d/lib-bash
source bash

# ## extensions::getVersion (private)
#
# Get the version of an extension.
#
# - $1: **extension directory** _as string_:
#       The directory of the extension for which we want to get the version.
#
function extensions::getVersion() {
  local extensionDirectory="${1}"

  local file
  for file in "version" "VERSION"; do
    if [[ -f ${extensionDirectory}/${file} ]]; then
      fs::readFile "${extensionDirectory}/${file}"
      string::trimAll REPLY
      return 0
    fi
  done

  if [[ ! -d ${extensionDirectory}/.git ]]; then
    REPLY=""
    return 0
  fi

  exe::invoke command git -C "${extensionDirectory}" rev-parse HEAD
  if ((REPLY_CODE != 0)); then
    REPLY=""
    return 0
  fi
  string::trimAll REPLY
  REPLY="${REPLY:0:7}"
}

# ## extensions::isSetupExecuted (private)
#
# Check if the setup script for an extension has been executed successfully.
#
# - $1: **extension directory** _as string_:
#       The directory of the extension for which we want to get the version.
# - $2: **version** _as string_ (optional):
#       The version of the extension to check. If not provided, the version will be computed using `extensions::getVersion`.
#
function extensions::isSetupExecuted() {
  local \
    extensionDirectory="${1}" \
    version="${2:-}"

  extensions::getSetupSuccessFile "${extensionDirectory}"
  local successFile="${REPLY}"

  if [[ ! -f ${successFile} ]]; then
    return 1
  fi

  if [[ -z ${version} ]]; then
    extensions::getVersion "${extensionDirectory}"
    version="${REPLY}"
  fi

  fs::readFile "${successFile}"
  string::trimAll REPLY
  if [[ ${REPLY} != "${version}" ]]; then
    return 1
  fi
}

# ## extensions::getSetupSuccessFile (private)
#
# Get the path to the file used to record the successful execution of the setup script for an extension.
#
# - $1: **extension directory** _as string_:
#       The directory of the extension for which we want to get the path to the setup success file.
#
function extensions::getSetupSuccessFile() {
  REPLY="${1}/.git/.valet-setup-executed"
}

# Execute the `extension.setup.sh` script of the extension, if any.
function extensions::executeSetupScript() {
  local \
    extensionDirectory="${1}" \
    unattended="${2}"

  extensions::getSetupSuccessFile "${extensionDirectory}"
  local \
    extensionName="${extensionDirectory##*/}" \
    successFile="${REPLY}"

  if [[ ! -f ${extensionDirectory}/extension.setup.sh ]]; then
    log::info "No ⌜extension.setup.sh⌝ script found in the extension directory ⌜${extensionDirectory}⌝."
    REPLY_CODE=0
    return 0
  fi

  log::info "Found setup script for the extension ${extensionName}: ⌜${extensionDirectory}/extension.setup.sh⌝."

  exe::invoke command rm -f "${successFile}"

  # ask for confirmation before executing the setup script
  if [[ ${unattended} != "true" ]] && ! interactive::confirm "The extension ⌜${extensionName}⌝ comes with a setup script usually used to finalize the installation."$'\n'"Make sure this script is safe to run before confirming this prompt."$'\n'$'\n'"Do you trust the setup script for the extension ⌜${extensionName}⌝ and wish to execute it?"; then
    log::info "The setup script for the extension ⌜${extensionName}⌝ was not trusted, skipping the setup."
    REPLY_CODE=0
    return 0
  fi

  log::info "Executing the setup script."
  # shellcheck disable=SC1091
  bash::runInSubshell source "${extensionDirectory}/extension.setup.sh"
  if ((REPLY_CODE != 0)); then
    log::error "The setup script for the extension ⌜${extensionName}⌝ failed."
    return 0
  else
    # record for which version we executed the setup script
    extensions::getVersion "${extensionDirectory}"
    local version="${REPLY}"
    fs::writeToFile "${successFile}" version
    if [[ -n ${version} ]]; then
      version=" (version ${version})"
    fi
    log::success "The setup script for the extension ⌜${extensionName}⌝${version} has been executed successfully."
  fi

  REPLY_CODE=0
}
