#!/usr/bin/env bash
# Title:          libraries.d/core
# Description:    this script contains the core functions and variables and it
#                 should be sourced, not called directly
# Author:         github.com/jcaillon

#===============================================================
# >>> Temporary files and folders
#===============================================================

# ## fs::setupTempFileGlobalVariable (private)
#
# Setup global variables that will be used for temporary files and folders.
function fs::setupTempFileGlobalVariable() {
  # get unique file names for the stdout, stderr and temporary directory
  # to be fast, we do not create anything until we really need it
  # this could lead to issues, although it is very unlikely
  GLOBAL_TEMPORARY_DIRECTORY_PREFIX="${VALET_CONFIG_TEMP_DIRECTORY:-${TMPDIR:-/tmp}}"
  GLOBAL_TEMPORARY_DIRECTORY_PREFIX="${GLOBAL_TEMPORARY_DIRECTORY_PREFIX%/}/vt-${BASHPID}"

  GLOBAL_TEMPORARY_FILE_PREFIX="${VALET_CONFIG_RUNTIME_DIRECTORY:-${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}}"
  if [[ ! -d ${GLOBAL_TEMPORARY_DIRECTORY_PREFIX} ]]; then
    command mkdir -p "${GLOBAL_TEMPORARY_DIRECTORY_PREFIX}" 1>/dev/null
  fi
  GLOBAL_TEMPORARY_FILE_PREFIX="${GLOBAL_TEMPORARY_FILE_PREFIX%/}/vt-${BASHPID}"

  while [[ -e "${GLOBAL_TEMPORARY_DIRECTORY_PREFIX}.d" ]]; do
    # just in case we have a collision
    GLOBAL_TEMPORARY_DIRECTORY_PREFIX+="x"
    GLOBAL_TEMPORARY_FILE_PREFIX+="x"
  done

  GLOBAL_TEMPORARY_DIRECTORY="${GLOBAL_TEMPORARY_DIRECTORY_PREFIX}.d"
  # shellcheck disable=SC2034
  GLOBAL_TEMPORARY_WORK_FILE="${GLOBAL_TEMPORARY_FILE_PREFIX}-work.f"
  # shellcheck disable=SC2034
  GLOBAL_TEMPORARY_STDOUT_FILE="${GLOBAL_TEMPORARY_FILE_PREFIX}-stdout.f"
  # shellcheck disable=SC2034
  GLOBAL_TEMPORARY_STDERR_FILE="${GLOBAL_TEMPORARY_FILE_PREFIX}-stderr.f"
  unset -v TEMPORARY_FILE_NUMBER TEMPORARY_DIRECTORY_NUMBER
}

# ## fs::setupSubshellTempFileGlobalVariable (private)
#
# Setup global variables that will be used for temporary files and folders in the context
# of a subshell. We keep everything under a new directory named with the process ID;
# the dir gets cleanup when the main process ends.
function fs::setupSubshellTempFileGlobalVariable() {
  TMPDIR="${GLOBAL_TEMPORARY_DIRECTORY}/job-${BASHPID}"
  command mkdir -p "${TMPDIR}" 1>/dev/null
  unset -v VALET_CONFIG_RUNTIME_DIRECTORY VALET_CONFIG_TEMP_DIRECTORY XDG_RUNTIME_DIR
  fs::setupTempFileGlobalVariable
}

# ## fs::createTempFile
#
# Creates a temporary file and return its path.
#
# - ${pathOnly} _as bool_:
#       (optional) If true, does not create the file, only returns the path.
#       (defaults to false)
#
# Returns:
#
# - ${REPLY}: The created path.
#
# ```bash
# fs::createTempFile
# echo "${REPLY}"
# fs::createTempFile pathOnly=true
# ```
#
# > Files created this way are automatically cleaned up by the fs::cleanTempFiles
# > function when valet ends.
function fs::createTempFile() {
  local \
    pathOnly="false" \
    IFS=$' '
  eval "local a= ${*@Q}"

  if [[ ! -v TEMPORARY_FILE_NUMBER ]]; then
    TEMPORARY_FILE_NUMBER=0
    if [[ ! -d ${GLOBAL_TEMPORARY_DIRECTORY} ]]; then
      command mkdir -p "${GLOBAL_TEMPORARY_DIRECTORY}" 1>/dev/null
    fi
  fi
  TEMPORARY_FILE_NUMBER=$((TEMPORARY_FILE_NUMBER + 1))
  REPLY="${GLOBAL_TEMPORARY_DIRECTORY}/f${TEMPORARY_FILE_NUMBER}-${BASH_SUBSHELL}"
  if [[ ${pathOnly} != "true" ]]; then
    : >"${REPLY}"
  fi
}

# ## fs::createTempDirectory
#
# Creates a temporary directory.
#
# - ${pathOnly} _as bool_:
#       (optional) If true, does not create the file, only returns the path.
#       (defaults to false)
#
# Returns:
#
# - ${REPLY}: The created path.
#
# ```bash
# fs::createTempDirectory
# echo "${REPLY}"
# fs::createTempDirectory pathOnly=true
# ```
#
# > Directories created this way are automatically cleaned up by the fs::cleanTempFiles
# > function when valet ends.
function fs::createTempDirectory() {
  local \
    pathOnly="false" \
    IFS=$' '
  eval "local a= ${*@Q}"

  if [[ ! -v TEMPORARY_DIRECTORY_NUMBER ]]; then
    TEMPORARY_DIRECTORY_NUMBER=0
    if [[ ${pathOnly} == "true" && ! -d ${GLOBAL_TEMPORARY_DIRECTORY} ]]; then
      command mkdir -p "${GLOBAL_TEMPORARY_DIRECTORY}" 1>/dev/null
    fi
  fi
  TEMPORARY_DIRECTORY_NUMBER=$((TEMPORARY_DIRECTORY_NUMBER + 1))
  REPLY="${GLOBAL_TEMPORARY_DIRECTORY}/d${TEMPORARY_DIRECTORY_NUMBER}-${BASH_SUBSHELL}"
  if [[ ${pathOnly} != "true" ]]; then
    command mkdir -p "${REPLY}" 1>/dev/null
  fi
}

# ## fs::cleanTempFiles
#
# Removes all the temporary files and directories that were created by the
# `fs::createTempFile` and `fs::createTempDirectory` functions.
#
# ```bash
# fs::cleanTempFiles
# ```
function fs::cleanTempFiles() {
  if [[ -d ${GLOBAL_TEMPORARY_DIRECTORY:-} ]]; then
    log::debug "Deleting temporary directory."
    command rm -rf "${GLOBAL_TEMPORARY_DIRECTORY}" &>/dev/null || :
  fi
  if [[ -n ${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY:-} && -d ${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY} ]]; then
    log::debug "Deleting temporary windows directory."
    command rm -rf "${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY}" &>/dev/null || :
  fi
  if [[ -n ${GLOBAL_TEMPORARY_FILE_PREFIX:-} ]]; then
    log::debug "Deleting temporary files."
    command rm -f "${GLOBAL_TEMPORARY_FILE_PREFIX}"* &>/dev/null || :
  fi
  unset -v TEMPORARY_FILE_NUMBER TEMPORARY_DIRECTORY_NUMBER
}

# TODO: create fs::cleanAllTempFiles which looks for existing temp files from older processes
# if not running then it is safe to delete

#===============================================================
# >>> Bash
#===============================================================

# ## bash::setShellOption
#
# Sets the given shell optional behavior if it is not already set.
# Allows to later use `bash::restoreShellOption` to restore the original state of the given shell option.
#
# - $1: **option name** _as string_:
#       The option to set (e.g. `nocasematch`).
#
# ```bash
# bash::setShellOption nocasematch
# ```
#
# > To set shell options, simply use `local -; set -/+ optionName` in functions (`local -` makes it local).
# > The builtin shopt cannot be scoped to a function (it is always global), this is why this function exists.
function bash::setShellOption() {
  local optionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  if ! shopt -q "${optionName}" &>/dev/null; then
    shopt -s "${optionName}"
    eval "_BASH_SHOPT_RESTORE_${optionName}='shopt -u ${optionName}'"
  else
    unset -v "_BASH_SHOPT_RESTORE_${optionName}"
  fi
}

# ## bash::unsetShellOption
#
# Unsets the given shell optional behavior if it is not already unset.
# Allows to later use `bash::restoreShellOption` to restore the original state of the given shell option.
#
# - $1: **option name** _as string_:
#      The option to unset (e.g. `nocasematch`).
#
# ```bash
# bash::unsetShellOption nocasematch
# ```
#
# > To unset shell options, simply use `local -; set -/+ optionName` in functions (`local -` makes it local).
# > The builtin shopt cannot be scoped to a function (it is always global), this is why this function exists.
function bash::unsetShellOption() {
  local optionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  if shopt -q "${optionName}" &>/dev/null; then
    shopt -u "${optionName}"
    eval "_BASH_SHOPT_RESTORE_${optionName}='shopt -s ${optionName}'"
  else
    unset -v "_BASH_SHOPT_RESTORE_${optionName}"
  fi
}

# ## bash::restoreShellOption
#
# Restores the given shell option to its original state (see `bash::setShellOption` or `bash::unsetShellOption`).
#
# - $1: **option name** _as string_:
#       The option to restore (e.g. `nocasematch`).
#
# ```bash
# bash::restoreShellOption nocasematch
# ```
function bash::restoreShellOption() {
  local optionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  if [[ -v _BASH_SHOPT_RESTORE_${optionName} ]]; then
    local -n restoreCommand="_BASH_SHOPT_RESTORE_${optionName}"
    eval "${restoreCommand}"
    unset -v "_BASH_SHOPT_RESTORE_${optionName}"
  fi
}

#===============================================================
# >>> Terminal UI
#===============================================================

# ## terminal::getTerminalSize
#
# This function exports the terminal size.
#
# Returns:
#
# - `GLOBAL_COLUMNS`: The number of columns in the terminal.
# - `GLOBAL_LINES`: The number of lines in the terminal.
#
# ```bash
# terminal::getTerminalSize
# printf '%s\n' "The terminal has ⌜${GLOBAL_COLUMNS}⌝ columns and ⌜${GLOBAL_LINES}⌝ lines."
# ```
# shellcheck disable=SC2034
function terminal::getTerminalSize() {
  if [[ ! -t ${GLOBAL_FD_TUI} ]]; then
    return 0
  fi
  {
    shopt -s checkwinsize
    # the following subshell is required to correctly compute the columns and lines
    # the bash manual says these are computed after the execution of an external command
    # but it works with a subshell
    (
      :
      :
    )
    GLOBAL_COLUMNS="${COLUMNS:-120}"
    GLOBAL_LINES="${LINES:-30}"
    shopt -u checkwinsize
  } 1>&"${GLOBAL_FD_TUI}" 2>&1
  # redirection to the terminal FD is necessary for bash to compute the terminal size
}

#===============================================================
# >>> String utilities
#===============================================================

# ## string::removeTextFormatting
#
# Removes all text formatting from the given string.
# This includes colors, bold, underline, etc.
#
# - $1: **text variable name** _as string_:
#       The variable name that contains the text to remove formatting from.
#
# ```bash
# string::removeTextFormatting "myText"
# echo "${myText}"
# ```
function string::removeTextFormatting() {
  local -n formattedString_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  if [[ ${formattedString_nameRef} == *$'\e'* ]]; then
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9][0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;5;[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;5;[0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;5;[0-9][0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9];[0-9];[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9][0-9];[0-9];[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9][0-9][0-9];[0-9];[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9];[0-9][0-9];[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9];[0-9][0-9][0-9];[0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9];[0-9];[0-9][0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9];[0-9];[0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9][0-9];[0-9][0-9];[0-9][0-9]m/}"
    formattedString_nameRef="${formattedString_nameRef//$'\e['[0-9]8;2;[0-9][0-9][0-9];[0-9][0-9][0-9];[0-9][0-9][0-9]m/}"
  fi
}

# ## string::wrapWords
#
# Allows to soft wrap the given text at the given width.
# Wrapping is done at word boundaries.
# Optionally appends padding characters on each new line.
#
# - $1: **text variable name** _as string_:
#       The variable name that contains the text to wrap.
# - ${width} _as string_:
#       (optional) The width to wrap the text at.
#       Note that length of the new line pad string is subtracted from the
#       width to make sure the text fits in the given width.
#       (defaults to "${GLOBAL_COLUMNS}")
# - ${newLinePadString} _as string_:
#       (optional) The characters to apply as padding on the left of each new line.
#       E.g. '  ' will add 2 spaces on the left of each new line.
#       (defaults to 0)
# - ${firstLineWidth} _as int_:
#       (optional) The width to use for the first line.
#       (defaults to "${width}")
#
# Returns:
#
# - ${REPLY}: the wrapped text
#
# ```bash
# string::wrapWords "This is a long text."
# string::wrapWords "This is a long text wrapped at 20 characters." width=20 newLinePadString="---" firstLineWidth=20
# echo "${REPLY}"
# ```
#
# > - This function is written in pure bash and is faster than calling the fold command.
# > - This function effectively trims all the extra spaces in the text (leading, trailing but also in the middle).
# > - It considers escape sequence for text formatting and does not count them as visible characters.
function string::wrapWords() {
  # make sure to turn off globbing to avoid expanding special characters like * or ? (local - makes set options local to the function)
  local -
  set -o noglob
  local -n stringToWrapAtWords_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    width="${GLOBAL_COLUMNS}" \
    newLinePadString="" \
    firstLineWidth \
    IFS=$' \t'
  shift 1
  eval "local a= ${*@Q}"

  firstLineWidth="${firstLineWidth:-${width}}"

  # short cut in case the text is already shorter than the width
  if [[ ${#stringToWrapAtWords_nameRef} -le ${firstLineWidth} && ${stringToWrapAtWords_nameRef} != *$'\n'* ]]; then
    REPLY="${stringToWrapAtWords_nameRef}"
    return 0
  fi

  local text="${stringToWrapAtWords_nameRef}"
  local output="" line word realWord REPLY2
  local leftPaddingVisibleChars="${newLinePadString}"
  string::removeTextFormatting leftPaddingVisibleChars
  local -i sentenceWidth=$((width - ${#leftPaddingVisibleChars})) realWordLength=0 firstWord=1
  local -i lineLength=$((sentenceWidth - firstLineWidth))

  while ((${#text} > 0)); do
    line="${text%%$'\n'*}"
    text="${text:${#line}+1}"

    output+=$'\n'"${newLinePadString}"

    # short cut in case the text is already shorter than the width
    if ((lineLength + ${#line} <= sentenceWidth)); then
      output+="${line}"
      continue
    fi

    firstWord=1

    for word in ${line}; do
      if [[ ${word} == *$'\e'* ]]; then
        realWord="${word}"
        string::removeTextFormatting realWord
        realWordLength="${#realWord}"
      else
        realWordLength="${#word}"
      fi

      if ((lineLength < sentenceWidth && firstWord == 0)); then
        output+=" "
        lineLength+=1
      else
        firstWord=0
      fi

      if ((lineLength + realWordLength <= sentenceWidth)); then
        # add the word to the current line
        output+="${word}"
        lineLength+=realWordLength
      else
        # not enough space left, check if the word fits on the next line
        if ((realWordLength <= sentenceWidth)); then
          output+=$'\n'"${newLinePadString}${word}"
          lineLength=realWordLength
        else
          # the word is too long to fit on a line, split it in multiple lines
          string::wrapCharacters word width="${width}" newLinePadString="${newLinePadString}" firstLineWidth="$((sentenceWidth - lineLength))"
          output+="${REPLY}"
          lineLength=${REPLY2}
        fi
      fi

    done

    lineLength=0
  done

  REPLY="${output#$'\n'"${newLinePadString}"}"
}

# ## string::wrapCharacters
#
# Allows to hard wrap the given string at the given width.
# Wrapping is done at character boundaries, see string::warpText for word wrapping.
# Optionally appends padding characters on each new line.
#
# - $1: **text variable name** _as string_:
#       The variable name that contains the text to wrap.
# - ${width} _as string_:
#       (optional) The width to wrap the text at.
#       Note that length of the new line pad string is subtracted from the
#       width to make sure the text fits in the given width.
#       (defaults to "${GLOBAL_COLUMNS}")
# - ${newLinePadString} _as string_:
#       (optional) The characters to apply as padding on the left of each new line.
#       E.g. '  ' will add 2 spaces on the left of each new line.
#       (defaults to 0)
# - ${firstLineWidth} _as int_:
#       (optional) The width to use for the first line.
#       (defaults to "${width}")
#
# Returns:
#
# - ${REPLY}: the wrapped string
# - ${REPLY2}: the length taken on the last line
#
# ```bash
# string::wrapCharacters "This-is-a-long-text"
# string::wrapCharacters "This-is-a-long-text-that-should-be-wrapped-at-20-characters." width=20 newLinePadString="---" firstLineWidth=5
# echo "${REPLY}"
# ```
#
# > - This function is written in pure bash and is faster than calling the fold command.
# > - It considers escape sequence for text formatting and does not count them as visible characters.
# > - Leading spaces after a newly wrapped line are removed.
function string::wrapCharacters() {
  local -n stringToWrapAtCharacters_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    width="${GLOBAL_COLUMNS}" \
    newLinePadString="" \
    firstLineWidth
  IFS=$' \t' \
    shift 1
  eval "local a= ${*@Q}"

  firstLineWidth="${firstLineWidth:-${width}}"

  local itemChunk spaces text="${stringToWrapAtCharacters_nameRef}"
  local leftPaddingVisibleChars="${newLinePadString}"
  string::removeTextFormatting leftPaddingVisibleChars
  width=$((width - ${#leftPaddingVisibleChars}))
  local -i lineLength=$((width - firstLineWidth)) isWrapping=0

  if ((width <= 0)); then
    REPLY=""
    REPLY2=0
    return
  fi

  REPLY=""
  while ((${#text} > 0)); do
    # take the first chunk that does not contain an escape character
    itemChunk="${text%%$'\e'*}"
    itemChunk="${itemChunk%%$'\n'*}"

    spaces="${itemChunk%%[^ ]*}"
    if [[ -n ${spaces} && lineLength -eq 0 && isWrapping -eq 1 ]]; then
      # if the chunk contains heading spaces, we can remove them
      itemChunk="${itemChunk:${#spaces}}"
      text="${text:${#spaces}}"
    fi

    if ((lineLength < width)); then
      itemChunk="${itemChunk:0:$((width - lineLength))}"
      text="${text:${#itemChunk}}"
      lineLength+=${#itemChunk}
      REPLY+="${itemChunk}"
      isWrapping=1

      while [[ ${text} == $'\e'* ]]; do
        # case where we have an escape sequence at the beginning of the string
        # we only consider escape sequences for text formatting, they end with 'm'
        itemChunk="${text%%"m"*}m"
        REPLY+="${itemChunk}"
        text="${text:${#itemChunk}}"
      done

      while [[ ${text} == $'\n'* ]]; do
        REPLY+=$'\n'"${newLinePadString}"
        text="${text:1}"
        lineLength=0
        isWrapping=0
      done
    fi

    if ((lineLength >= width)); then
      # we reached the desired size
      lineLength=0
      REPLY+=$'\n'"${newLinePadString}"
    fi
  done

  REPLY="${REPLY%$'\n'"${newLinePadString}"}"
  REPLY2=${lineLength}
}

# ## string::highlight
#
# Highlight characters in a string.
#
# - $1: **text variable name** _as string_:
#       The variable name that contains the text to highlight.
# - $2: **characters variable name** _as string_:
#       The variable name that contains characters to highlight.
# - ${highlightCode} _as string_:
#       (optional) The ANSI code to use for highlighting.
#       The default value can be set using the variable STYLE_COLOR_ACCENT.
#       (defaults to $'\e'"[95m"}")
# - ${resetCode} _as string_:
#       (optional) The ANSI code to use for resetting the highlighting.
#       The default value can be set using the variable STYLE_COLOR_DEFAULT.
#       (defaults to $'\e'"[0m")
#
# Returns:
#
# - ${REPLY}: the highlighted text
#
# ```bash
# string::highlight "This is a text to highlight." "ttttt"
# echo "${REPLY}"
# ```
#
# > - All characters to highlight must be found in the same order in the matched line.
# > - This functions is case insensitive.
function string::highlight() {
  local -n \
    textToHighlight_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    charactersToHighlight_nameRef="${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    highlightCode="${STYLE_COLOR_ACCENT:-$'\e'"[95m"}" \
    resetCode="${STYLE_COLOR_DEFAULT:-$'\e'"[0m"}"
  IFS=$' '
  shift 2
  eval "local a= ${*@Q}"

  local itemChunk itemChunkPiece
  local -i searchStringIndex=0
  local searchStringCharacter="${charactersToHighlight_nameRef:0:1}"
  local searchStringCharacters="${searchStringCharacter,}${searchStringCharacter^}"
  local text="${textToHighlight_nameRef}"

  REPLY=""

  while ((${#text} > 0)); do
    # take the first chunk that does not contain an escape character
    itemChunk="${text%%$'\e'*}"
    text="${text:${#itemChunk}}"

    if [[ -n ${itemChunk} ]]; then
      # colorize the search string in this chunk
      while [[ -n ${searchStringCharacter} && ${itemChunk} == *["${searchStringCharacters}"]* ]]; do
        itemChunkPiece="${itemChunk%%["${searchStringCharacters}"]*}"
        REPLY+="${itemChunkPiece}${highlightCode}${itemChunk:${#itemChunkPiece}:1}${resetCode}"
        itemChunk="${itemChunk:${#itemChunkPiece}+1}"
        searchStringIndex+=1
        searchStringCharacter="${charactersToHighlight_nameRef:searchStringIndex:1}"
        searchStringCharacters="${searchStringCharacter,}${searchStringCharacter^}"
      done

      REPLY+="${itemChunk}"
    fi

    while [[ ${text} == $'\e'* ]]; do
      # case where we have an escape sequence at the beginning of the string
      # we only consider escape sequences for text formatting, they end with m
      itemChunk="${text%%"m"*}m"
      REPLY+="${itemChunk}"
      text="${text:${#itemChunk}}"
    done
  done
}

# ## string::numberToUniqueId
#
# Converts a number into a unique and human readable string of the same length.
#
# - $1: **number** _as int_:
#       The number to convert.
#
# Returns:
#
# - ${REPLY}: the unique string.
#
# ```bash
# string::numberToUniqueId 12345
# echo "${REPLY}"
# ```
function string::numberToUniqueId() {
  local number="${1}"

  # we convert numbers
  local vowels="aeiou"
  local consonants="bcdfmnprstgjklvwxz"
  REPLY=""
  local toConvert
  local -i index=0
  while ((index < ${#number})); do
    toConvert="${number:index:2}"
    if ((${#toConvert} == 2)); then
      REPLY+="${consonants:$((10#${toConvert} / 5 - 2)):1}${vowels:$((10#${toConvert} % 5)):1}"
    elif ((${#toConvert} == 1)); then
      REPLY+="${consonants:toConvert:1}"
    fi
    index+=2
  done
}

#===============================================================
# >>> Regex utilities
#===============================================================

# ## regex::getFuzzySearchRegexFromSearchString
#
# Allows to get a regex that can be used to fuzzy search a string.
# the -> '([^t]*)(t[^h]*h[^e]*e)'
#
# - $1: **search string** _as string_:
#       The variable name containing the search string to match.
#
# Returns:
#
# - ${_STRING_FUZZY_FILTER_REGEX}: the regex
#
# ```bash
# regex::getFuzzySearchRegexFromSearchString SEARCH_STRING
# echo "${_STRING_FUZZY_FILTER_REGEX}"
# ```
function regex::getFuzzySearchRegexFromSearchString() {
  local -n filterString_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"

  # nothing to filter
  if [[ -z ${filterString_nameRef} ]]; then
    _STRING_FUZZY_FILTER_REGEX=""
    return 0
  fi

  # \^$.|?*+[]{}()
  local escapedCharacter

  # prepare the regex for the searched string
  _STRING_FUZZY_FILTER_REGEX=""
  local -i index
  for ((index = 0; index < ${#filterString_nameRef}; index++)); do
    escapedCharacter=${filterString_nameRef:index:1}
    if [[ '\^$.|?*+[]{}()' == *"${escapedCharacter}"* ]]; then
      escapedCharacter="\\"${escapedCharacter}
    fi
    if ((index == 0)); then
      _STRING_FUZZY_FILTER_REGEX+="^([^${filterString_nameRef:index:1}]"'*'")(${escapedCharacter}"
    else
      _STRING_FUZZY_FILTER_REGEX+="[^${filterString_nameRef:index:1}]"'*'"${escapedCharacter}"
    fi
  done

  _STRING_FUZZY_FILTER_REGEX+=")(.?)"
}

#===============================================================
# >>> Array utilities
#===============================================================

# ## array::fuzzyFilterSort
#
# Allows to fuzzy sort an array against a given searched string.
# Returns an array containing only the lines matching the searched string.
# The array is sorted by (in order):
#
# - the index of the first matched character in the line
# - the distance between the first and last matched characters in the line
# - the original order in the list
#
# Also returns an array containing the indexes of the matched items in the original array.
#
# - $1: **array name** _as string_:
#       The array name to fuzzy filter and sort.
# - $2: **search string** _as string_:
#       The variable name containing the search string to match.
#
# Returns:
#
# - ${REPLY_ARRAY[@]}: An array containing the items sorted and filtered
# - ${REPLY_ARRAY2[@]}: An array containing the indexes of the matched items in the original array
#
# ```bash
# array::fuzzyFilterSort MY_ARRAY SEARCH_STRING
# echo "${REPLY_ARRAY[*]}"
# ```
#
# > - All characters in the searched string must be found in the same order in the matched line.
# > - Use `shopt -s nocasematch` to make this function is case insensitive.
# > - This function is not appropriate for large arrays (>10k elements), see `array::fuzzyFilterSortFileWithGrepAndGawk` for large arrays.
function array::fuzzyFilterSort() {
  local -n \
    arrayToFilter_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    filterString_nameRef="${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"

  # nothing to filter
  if ((${#filterString_nameRef} == 0 || ${#arrayToFilter_nameRef[@]} == 0)); then
    REPLY_ARRAY=("${arrayToFilter_nameRef[@]}")
    eval "REPLY_ARRAY2=( {0..$((${#arrayToFilter_nameRef[@]} - 1))} )"
    return 0
  fi

  regex::getFuzzySearchRegexFromSearchString "${2}"

  # will contain a key that allows to sort the items, it is a combination of the length before the pattern,
  # the length of the matched pattern and the initial position of the item
  _ARRAY_FUZZY_FILTER_KEYS=()
  # will contain the original indexes corresponding to the sorted array
  REPLY_ARRAY2=()

  for ((index = 0; index < ${#arrayToFilter_nameRef[@]}; index++)); do
    if [[ ${arrayToFilter_nameRef[index]} =~ ${_STRING_FUZZY_FILTER_REGEX} ]]; then
      if ((${#BASH_REMATCH[3]} == 0 && ${#BASH_REMATCH[1]} == 0)); then
        _ARRAY_FUZZY_FILTER_KEYS+=($((index)))
      else
        _ARRAY_FUZZY_FILTER_KEYS+=($((${#BASH_REMATCH[1]} * 10000000 + ${#BASH_REMATCH[2]} * 10000 + index)))
      fi
      REPLY_ARRAY2+=($((index)))
    fi
  done

  if ((${#_ARRAY_FUZZY_FILTER_KEYS[@]} > 1)); then
    array_fuzzyFilterSortQuicksort 0 $((${#_ARRAY_FUZZY_FILTER_KEYS[@]} - 1))
  fi

  # will contain the matched lines, sorted
  REPLY_ARRAY=()
  for ((index = 0; index < ${#REPLY_ARRAY2[@]}; index++)); do
    REPLY_ARRAY+=("${arrayToFilter_nameRef[REPLY_ARRAY2[index]]}")
  done
  unset -v _ARRAY_FUZZY_FILTER_KEYS
}

# ## array_fuzzyFilterSortQuicksort (private)
#
# A special quicksort implementation dedicated to `array::fuzzyFilterSort`
# that only compare numbers and that uses _ARRAY_FUZZY_FILTER_KEYS as
# a global arrays to go faster. Check `array::quicksort` for an equivalent
# but clearer implementation.
#
# - $1: **low** _as int_:
#       The low index of the _ARRAY_FUZZY_FILTER_KEYS array.
# - $2: **high** _as int_:
#       The high index of the _ARRAY_FUZZY_FILTER_KEYS array.
#
# ```bash

# array_fuzzyFilterSortQuicksort 0 $((${#_ARRAY_FUZZY_FILTER_KEYS[@]} - 1))
# ```
function array_fuzzyFilterSortQuicksort() {
  local -i left=${1} right=${2} tempValue pivotValue=${_ARRAY_FUZZY_FILTER_KEYS[${1} + (${2} - ${1}) / 2]}
  while :; do
    while ((_ARRAY_FUZZY_FILTER_KEYS[left] < pivotValue)); do
      left+=1
    done
    while ((pivotValue < _ARRAY_FUZZY_FILTER_KEYS[right])); do
      right=$((right - 1))
    done
    if ((left >= right)); then
      break
    fi
    tempKey=${_ARRAY_FUZZY_FILTER_KEYS[left]}
    _ARRAY_FUZZY_FILTER_KEYS[left]=${_ARRAY_FUZZY_FILTER_KEYS[right]}
    _ARRAY_FUZZY_FILTER_KEYS[right]=${tempKey}
    tempValue=${REPLY_ARRAY2[left]}
    REPLY_ARRAY2[left]=${REPLY_ARRAY2[right]}
    REPLY_ARRAY2[right]=${tempValue}
    left+=1
    right=$((right - 1))
  done
  if ((${1} < right)); then
    array_fuzzyFilterSortQuicksort "${1}" ${right}
  fi
  if ((right + 1 < ${2})); then
    array_fuzzyFilterSortQuicksort $((right + 1)) "${2}"
  fi
}

#===============================================================
# >>> Time utilities
#===============================================================

# ## time::getProgramElapsedMicroseconds
#
# Get the elapsed time in µs since the program started.
#
# Returns:
#
# - ${REPLY}: the elapsed time in µs since the program started.
#
# ```bash
# time::getProgramElapsedMicroseconds
# echo "${REPLY}"
# time::getHumanTimeFromMicroseconds "${REPLY}"
# echo "Human time: ${REPLY}"
# ```
#
# > We split the computation in seconds and milliseconds to avoid overflow on 32-bit systems.
# > The 10# forces the base 10 conversion to avoid issues with leading zeros.
# > Fun fact: this function will fail in 2038 on 32-bit systems because the number of seconds will overflow.
function time::getProgramElapsedMicroseconds() {
  # the eval is here because sometimes bash does not expand the EPOCHREALTIME variable correctly, idk why
  eval "REPLY=\$(((${EPOCHREALTIME%%[.,]*} - GLOBAL_PROGRAM_STARTED_AT_SECOND) * 1000000 + (10#${EPOCHREALTIME##*[.,]} - 10#${GLOBAL_PROGRAM_STARTED_AT_MICROSECOND})))"
}

#===============================================================
# >>> Styles functions
#===============================================================

# ## styles::init (private)
#
# Initialize the valet styles variables.
# Also includes the esc-codes library (required for styles).
function styles::init() {
  builtin source "${GLOBAL_INSTALLATION_DIRECTORY}/libraries.d/core-esc-codes"
  builtin source "${GLOBAL_INSTALLATION_DIRECTORY}/libraries.d/core-styles"
}

#===============================================================
# >>> Command functions (called from user command functions)
#===============================================================

# ## command::sourceFunction
#
# Source the file associated with a command function.
# This allows you to call a command function without having to source the file manually.
#
# - $1: **function name** _as string_:
#       the function name
#
# ```bash
# command::sourceFunction "functionName"
# ```
function command::sourceFunction() {
  local functionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"

  # shellcheck disable=SC1091
  source command

  command::sourceCommandFunction "${functionName}"
}

# ## command::parseArguments
#
# Parse the arguments and options of a function and return a string that can be evaluated to set the variables.
# This should be called from a command function for which you want to parse the arguments.
#
# See the documentation for more details on the parser: <https://jcaillon.github.io/valet/docs/new-commands/#-implement-your-command>.
#
#
# - $@: **arguments** _as any_:
#       the arguments to parse
#
# Returns:
#
# - ${REPLY}: a string that can be evaluated to set the parsed variables
#
# Output example:
#
# ```
# local arg1 option1
# arg1="xxx"
# option1="xxx"
# ```
#
# ```bash
# command::parseArguments "$@"; eval "${REPLY}"
# ```
function command::parseArguments() {
  # get the function name of the calling function
  local functionName="${FUNCNAME[1]?"This function must be called from a command function."}"

  # shellcheck disable=SC1091
  source command

  command::parseCmdFunctionArgumentsOrGoInteractive "${functionName}" "$@"
}

# ## command::checkParsedResults
#
# A convenience function to check the parsing results and fails with an error message if there are
# parsing errors.
# Will also display the help if the help option is true.
#
# This should be called from a command function for which you want to check the parsing results.
#
# It uses the variables `help` and `commandArgumentsErrors` to determine if the help should be displayed
# and if there are parsing errors.
#
# ```bash
# command::checkParsedResults
# ```
function command::checkParsedResults() {
  if [[ ${help:-false} == "true" ]]; then
    # shellcheck disable=SC1091
    source command
    command::printHelp function "${FUNCNAME[1]?"This function must be called from a command function."}"
    core::exit 0 silent=true
  fi
  if [[ -n ${commandArgumentsErrors:-} ]]; then
    core::fail "${commandArgumentsErrors}"
  fi
}

# ## command::showHelp
#
# Show the help for the current function.
# This should be called directly from a command function for which you want to display the help text.
#
# ```bash
# command::showHelp
# ```
function command::showHelp() {
  local functionName
  # get the function name of the calling function
  functionName="${FUNCNAME[1]?"This function must be called from a command function."}"

  # shellcheck disable=SC1091
  source command

  command::printHelp function "${functionName}"
}
