#!/usr/bin/env bash
# Title:          libraries.d/core
# Description:    this script contains the core functions and variables and it
#                 should be sourced, not called directly
# Author:         github.com/jcaillon

#===============================================================
# >>> Logging
#===============================================================

# ## log::setLevel
#
# Set the log level.
#
# - $1: **log level** _as string_:
#       The log level to set (or defaults to info), acceptable values are:
#         - trace
#         - debug
#         - info
#         - success
#         - warning
#         - error
# - ${silent} _as bool_:
#       (optional) true to silently switch log level, i.e. does not print a message
#       (defaults to false)
#
# ```bash
# log::setLevel debug
# log::setLevel debug silent=true
# ```
function log::setLevel() {
  GLOBAL_LOG_LEVEL="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    silent="false" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  # lowercase the log level
  GLOBAL_LOG_LEVEL="${GLOBAL_LOG_LEVEL,,}"

  # log level, defaults to info
  case "${GLOBAL_LOG_LEVEL}" in
  error) GLOBAL_LOG_LEVEL_INT=4 ;;
  warning) GLOBAL_LOG_LEVEL_INT=3 ;;
  success) GLOBAL_LOG_LEVEL_INT=2 ;;
  info) GLOBAL_LOG_LEVEL_INT=1 ;;
  debug) GLOBAL_LOG_LEVEL_INT=0 ;;
  trace) GLOBAL_LOG_LEVEL_INT=-1 ;;
  *) core::fail "Unknown log level: ${GLOBAL_LOG_LEVEL}" ;;
  esac

  if [[ ${silent} != "true" ]]; then
    if ((GLOBAL_LOG_LEVEL_INT != 1)); then
      log::debug "Log level set to ${GLOBAL_LOG_LEVEL}."
    fi
    if ((GLOBAL_LOG_LEVEL_INT <= 0)); then
      log::warning "Beware that debug log level might lead to secret leak, use it only if necessary."
    fi
  fi
}

# ## log::getLevel
#
# Get the current log level.
#
# Returns:
#
# - ${REPLY}: The current log level.
#
# ```bash
# log::getLevel
# printf '%s\n' "The log level is ⌜${REPLY}⌝."
# ```
function log::getLevel() {
  REPLY="${GLOBAL_LOG_LEVEL:-info}"
}

# ## log::print (private)
#
# Display a log message.
#
# - $1: **color name** _as string_:
#       The color name to use for the severity (TRACE, DEBUG...).
# - $2: **icon** _as string_:
#       The icon to display in the log message (utf8 character from nerd icons).
# - $3: **severity** _as string_:
#       The severity to display (max 7 chars for the default log pattern).
# - $4: **message** _as string_:
#       The message to log.
#
# ```bash
# log::print "SUCCESS" $'\uf14a' "OK" "This is a success message."
# ```
# shellcheck disable=SC2034
function log::print() {
  local \
    colorName="${1}" \
    icon="${2}" \
    level="${3}" \
    messageToLog="${4}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::error
#
# Displays an error message.
#
# - $1: **message** _as string_:
#       the error messages to display
#
# ```bash
# log::error "This is an error message."
# ```
#
# > You probably want to exit immediately after an error and should consider using core::fail function instead.
function log::error() {
  # shellcheck disable=SC2034
  local \
    colorName="ERROR" \
    icon="${ICON_ERROR:-}" \
    level="ERROR" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"

  if log::isDebugEnabled; then
    log::printCallStack
  fi
}

# ## log::warning
#
# Displays a warning.
#
# - $1: **message** _as string_:
#       the warning messages to display
#
# ```bash
# log::warning "This is a warning message."
# ```
function log::warning() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} > 3)); then
    return 0
  fi
  # shellcheck disable=SC2034
  local \
    colorName="WARNING" \
    icon="${ICON_WARNING:-}" \
    level="WARNING" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::success
#
# Displays a success message.
#
# - $1: **message** _as string_:
#       the success messages to display
#
# ```bash
# log::success "This is a success message."
# ```
function log::success() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} > 2)); then
    return 0
  fi
  # shellcheck disable=SC2034
  local \
    colorName="SUCCESS" \
    icon="${ICON_SUCCESS:-}" \
    level="SUCCESS" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::info
#
# Displays an info message.
#
# - $1: **message** _as string_:
#       the info messages to display
#
# ```bash
# log::info "This is an info message."
# ```
function log::info() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} > 1)); then
    return 0
  fi
  # shellcheck disable=SC2034
  local \
    colorName="INFO" \
    icon="${ICON_INFO:-}" \
    level="INFO" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::debug
#
# Displays a debug message.
#
# - $1: **message** _as string_:
#       the debug messages to display
#
# ```bash
# log::debug "This is a debug message."
# ```
function log::debug() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} > 0)); then
    return 0
  fi
  # shellcheck disable=SC2034
  local \
    colorName="DEBUG" \
    icon="${ICON_DEBUG:-}" \
    level="DEBUG" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::trace
#
# Displays a trace message.
#
# - $1: **message** _as string_:
#       the trace messages to display
#
# ```bash
# log::trace "This is a trace message."
# ```
function log::trace() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} > -1)); then
    return 0
  fi
  # shellcheck disable=SC2034
  local \
    colorName="TRACE" \
    icon="${ICON_TRACE:-}" \
    level="TRACE" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::errorTrace
#
# Displays an error trace message.
# This is a trace message that is always displayed, independently of the log level.
# It can be used before a fatal error to display useful information.
#
# - $1: **message** _as string_:
#       the trace messages to display
#
# ```bash
# log::errorTrace "This is a debug message."
# ```
function log::errorTrace() {
  # shellcheck disable=SC2034
  local \
    colorName="TRACE" \
    icon="${ICON_TRACE:-}" \
    level="TRACE" \
    messageToLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # evaluated the print statement built in log::init; it uses the local vars defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}"
}

# ## log::isDebugEnabled
#
# Check if the debug mode is enabled.
#
# Returns:
#
# - $?:
#   - 0 if debug mode is enabled (log level is debug)
#   - 1 if disabled
#
# ```bash
# if log::isDebugEnabled; then printf '%s\n' "Debug mode is active."; fi
# ```
function log::isDebugEnabled() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} <= 0)); then
    return 0
  fi
  return 1
}

# ## log::isTraceEnabled
#
# Check if the trace mode is enabled.
#
# Returns:
#
# - $?:
#   - 0 if trace mode is enabled (log level is trace)
#   - 1 if disabled
#
# ```bash
# if log::isTraceEnabled; then printf '%s\n' "Debug mode is active."; fi
# ```
function log::isTraceEnabled() {
  if ((${GLOBAL_LOG_LEVEL_INT:-1} <= -1)); then
    return 0
  fi
  return 1
}

# ## log::printTrappedBashCommand (private)
#
# This function prints the current bash command when called from a trap.
function log::printTrappedBashCommand() {
  local \
    symbol="╰" \
    command="${BASH_COMMAND:-}"
  if [[ -n ${FUNCNAME[2]:-} ]]; then
    symbol="╭"
  fi
  if [[ -n ${GLOBAL_LAST_BASH_COMMAND:-} ]]; then
    command="${GLOBAL_LAST_BASH_COMMAND}"
  fi
  log::printString "${symbol} ${command}" newLinePadString="│ "
}

# ## log::printCallStack
#
# This function prints the current function stack in the logs.
#
# - ${stackToSkip} _as int_:
#       (optional) The number of stack to skip.
#       For instance, a value of 2 will skip this function and the first calling function.
#       (defaults to 2)
# - ${stackToSkipAtEnd} _as int_:
#       (optional) The number of stack to skip at the end.
#       (defaults to 0)
#
# ```bash
# log::printCallStack
# log::printCallStack stackToSkip=0
# ```
#
# > For test purposes, you can set the `GLOBAL_MOCK_STACK_FUNCTION_NAMES`, `GLOBAL_MOCK_STACK_SOURCE_FILES` and `GLOBAL_MOCK_STACK_LINE_NUMBERS`
# > variables to simulate a call stack.
# shellcheck disable=SC2120
function log::printCallStack() {
  local \
    stackToSkip=2 \
    stackToSkipAtEnd=0 \
    IFS=$' '
  eval "local a= ${*@Q}"

  log::getCallStack stackToSkip="$((stackToSkip + 1))" stackToSkipAtEnd="${stackToSkipAtEnd}" wrapWidth="$((${GLOBAL_LOG_COLUMNS:-${GLOBAL_COLUMNS}} - ${#GLOBAL_LOG_WRAP_PADDING}))"
  if ((${#REPLY} > 0)); then
    log::printString "${REPLY}"
  fi
}

# ## log::getCallStack
#
# This function returns the current function stack.
#
# - ${stackToSkip} _as int_:
#       (optional) The number of stack to skip.
#       For instance, a value of 1 will skip this function.
#       (defaults to 1)
# - ${stackToSkipAtEnd} _as int_:
#       (optional) The number of stack to skip at the end.
#       (defaults to 0)
# - ${wrapWidth} _as int_:
#       (optional) The width to wrap the call stack.
#       (defaults to 0)
#
# Returns:
#
# - ${REPLY}: The call stack as a string.
#
# ```bash
# log::getCallStack
# echo "${REPLY}"
# log::getCallStack stackToSkip=2 stackToSkipAtEnd=1 wrapWidth=80
# ```
#
# > For test purposes, you can set the `GLOBAL_MOCK_STACK_FUNCTION_NAMES`, `GLOBAL_MOCK_STACK_SOURCE_FILES` and `GLOBAL_MOCK_STACK_LINE_NUMBERS`
# > variables to simulate a call stack.
function log::getCallStack() {
  local \
    stackToSkip=1 \
    stackToSkipAtEnd=0 \
    wrapWidth=0 \
    IFS=$' '
  eval "local a= ${*@Q}"

  local -a stackFunctionNames stackSourceFiles stackLineNumbers
  if [[ -n ${GLOBAL_MOCK_STACK_FUNCTION_NAMES:-} ]]; then
    stackFunctionNames=("${GLOBAL_MOCK_STACK_FUNCTION_NAMES[@]}")
    stackSourceFiles=("${GLOBAL_MOCK_STACK_SOURCE_FILES[@]}")
    stackLineNumbers=("${GLOBAL_MOCK_STACK_LINE_NUMBERS[@]}")
  else
    stackFunctionNames=("${FUNCNAME[@]}")
    stackSourceFiles=("${BASH_SOURCE[@]}")
    stackLineNumbers=("${BASH_LINENO[@]}")
  fi

  local -i idx stackSize=$((${#stackFunctionNames[@]} - stackToSkipAtEnd))
  local functionName lineNumber="${LINENO}" sourceFile line returnedString=""
  local treeString="├─" treePadding="│  "
  for ((idx = stackToSkip; idx < stackSize; idx++)); do
    functionName="${stackFunctionNames[${idx}]}"
    if [[ -z ${functionName} ]]; then
      functionName=ROOT
    else
      functionName="${functionName}()"
    fi
    if ((idx > 0)); then
      lineNumber="${stackLineNumbers[idx - 1]}"
    fi
    sourceFile="${stackSourceFiles[${idx}]}"
    if [[ -z ${sourceFile} ]]; then
      sourceFile=ROOT
    fi
    sourceFile="${sourceFile#"./"}"
    sourceFile="${sourceFile#"${GLOBAL_PROGRAM_STARTED_AT_DIRECTORY}/"}"
    if ((idx == stackSize - 1)); then
      treeString="╰─"
      treePadding="   "
    fi
    line="${treeString} in ${functionName} at ${sourceFile}:${lineNumber}"
    if ((wrapWidth > 0)); then
      local REPLY2
      string::wrapCharacters line width="${wrapWidth}" newLinePadString="${treePadding}"
      returnedString+="${REPLY}"$'\n'
    else
      returnedString+="${line}"$'\n'
    fi
  done

  REPLY="${returnedString}"
}

# ## log::printFile
#
# Display a file content with line numbers in the logs.
# The file content will be aligned with the current log output and hard wrapped if necessary.
#
# - $1: **path** _as string_:
#       the file path to display.
# - ${maxLines} _as int_:
#       (optional) Max lines to display, can be set to 0 to display all lines.
#       (defaults to 0)
#
# ```bash
# log::printFile "/my/file/path"
# log::printFile "/my/file/path" maxLines=10
# ```
# shellcheck disable=SC2317
function log::printFile() {
  local \
    filePath="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    maxLines="0" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  local REPLY_CODE REPLY REPLY2 line rawStringToPrintInLog lineNumberPadding="   "
  local -i lineNumber=1 currentLineNumberLength=1
  if [[ ! -f "${filePath}" ]]; then
    log::error "Can not print the file ⌜${filePath}⌝ because does not exist."
    return 0
  fi

  while IFS=$'\n' read -rd $'\n' line || [[ -n ${line:-} ]]; do
    log::printFileInternalLoop
    if ((REPLY_CODE != 0)); then
      break
    fi
  done <"${filePath}"

  # evaluated the print statement built in log::init; it uses the local var rawStringToPrintInLog defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_STANDARD}"
}

# ## log::printFileString
#
# Display a file content with line numbers in the logs.
# The file content will be aligned with the current log output and hard wrapped if necessary.
#
# - $1: **content variable name** _as string_:
#       The name of the variable containing the file content to print.
# - ${maxLines} _as int_:
#       (optional) Max lines to display, can be set to 0 to display all lines.
#       (defaults to 0)
#
# ```bash
# log::printFileString "myvar"
# log::printFileString "myvar" maxLines=10
# ```
#
# > This function is not at all suited for large strings, print the content to a file instead.
# shellcheck disable=SC2317
function log::printFileString() {
  local -n content_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    maxLines="0" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  local REPLY_CODE REPLY REPLY2 line rawStringToPrintInLog lineNumberPadding="   "
  local -i lineNumber=1 currentLineNumberLength=1

  while IFS=$'\n' read -rd $'\n' line; do
    log::printFileInternalLoop
    if ((REPLY_CODE != 0)); then
      break
    fi
  done <<<"${content_nameRef}"

  # evaluated the print statement built in log::init; it uses the local var rawStringToPrintInLog defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_STANDARD}"
}

# ## log::printFileInternalLoop (private)
#
# An internal function used in log::printFile and log::printFileString to display each line
# of a file or string. It uses the local variables set by the calling function.
function log::printFileInternalLoop() {
  if [[ ${GLOBAL_LOG_DISABLE_WRAP} != "true" ]]; then
    string::wrapCharacters line width="${GLOBAL_LOG_COLUMNS}" newLinePadString="${GLOBAL_LOG_WRAP_PADDING}     ${STYLE_COLOR_FADED}░${STYLE_COLOR_DEFAULT} " firstLineWidth=$((GLOBAL_LOG_COLUMNS - 7 - ${#GLOBAL_LOG_WRAP_PADDING}))

    rawStringToPrintInLog+="${GLOBAL_LOG_WRAP_PADDING}${STYLE_COLOR_FADED}${lineNumberPadding}${lineNumber} ░${STYLE_COLOR_DEFAULT} ${REPLY}"$'\n'
  else
    rawStringToPrintInLog+="${STYLE_COLOR_FADED}${lineNumberPadding}${lineNumber} ░${STYLE_COLOR_DEFAULT} ${line}"$'\n'
  fi

  lineNumber+=1
  if ((${#lineNumber} > currentLineNumberLength)); then
    lineNumberPadding="${lineNumberPadding%?}"
    currentLineNumberLength+=1
  fi
  if ((maxLines != 0 && lineNumber > maxLines)); then
    if [[ ${GLOBAL_LOG_DISABLE_WRAP} != "true" ]]; then
      rawStringToPrintInLog+="${GLOBAL_LOG_WRAP_PADDING}"
    fi
    rawStringToPrintInLog+="${STYLE_COLOR_FADED}     ░ (truncated)${STYLE_COLOR_DEFAULT}"$'\n'
    REPLY_CODE=1
    return 0
  fi
  REPLY_CODE=0
}

# ## log::printString
#
# Display a string in the log.
# The string will be aligned with the current log output and hard wrapped if necessary.
# Does not check the log level.
#
# - $1: **content** _as string_:
#       the content to log (can contain new lines)
# - ${newLinePadString} _as string_:
#       (optional) the string with which to prepend each wrapped line
#       (defaults to "")
#
# ```bash
# log::printString "my line"
# log::printString "my line" newLinePadString="  "
# ```
# shellcheck disable=SC2317
function log::printString() {
  local \
    content="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    newLinePadString="" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  local REPLY REPLY2 line rawStringToPrintInLog
  while [[ -n ${content} ]]; do
    line="${content%%$'\n'*}"
    content="${content:${#line}+1}"

    if [[ ${GLOBAL_LOG_DISABLE_WRAP} != "true" ]]; then
      string::wrapCharacters line width="${GLOBAL_LOG_COLUMNS}" newLinePadString="${GLOBAL_LOG_WRAP_PADDING}${newLinePadString}" firstLineWidth="$((GLOBAL_LOG_COLUMNS - ${#GLOBAL_LOG_WRAP_PADDING}))"
      rawStringToPrintInLog+="${GLOBAL_LOG_WRAP_PADDING}${REPLY}"$'\n'
    else
      rawStringToPrintInLog+="${line}"$'\n'
    fi
  done
  # evaluated the print statement built in log::init; it uses the local var rawStringToPrintInLog defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_STANDARD}"
}

# ## log::saveFile
#
# Save the given file by copying it to a new file in the user local state directory
# (using `core::createSavedFilePath`).
# Useful for debugging purposes, to save the state of a file during execution.
#
# - $1: **path** _as string_:
#       The file path to save.
# - ${suffix} _as string_:
#       (optional) The suffix for the file to create.
#       (defaults to "")
# - ${silent} _as bool_:
#       (optional) if true, do not log the path of the saved file using `log::printString`
#       (defaults to false)
#
# Returns:
#
# - ${REPLY}: The path to the saved file.
#
# ```bash
# log::saveFile "/my/file/path" "suffix" "important result file"
# ```
function log::saveFile() {
  local \
    filePath="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    suffix="" \
    silent="false" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  core::createSavedFilePath suffix="${suffix}"
  local newFilePath="${REPLY}"
  command cp "${filePath}" "${newFilePath}"
  if [[ ${silent} != "true" ]]; then
    log::printString "${newFilePath}"
  fi
  REPLY="${newFilePath}"
}

# ## log::saveFileString
#
# Save the given string to a new file in the user local state directory
# (using `core::createSavedFilePath`).
# Useful for debugging purposes, to save the state of a string during execution.
#
# - $1: **content variable name** _as string_:
#       The variable name of the content to save.
# - ${suffix} _as string_:
#       (optional) The suffix for the file to create.
#       (defaults to "")
# - ${silent} _as bool_:
#       (optional) if true, do not log the path of the saved file using `log::printString`
#       (defaults to false)
#
# Returns:
#
# - ${REPLY}: The path to the saved file.
#
# ```bash
# log::saveFileString "my content" "suffix" "important result file"
# ```
function log::saveFileString() {
  local -n content_nameRef="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local \
    suffix="" \
    silent="false" \
    IFS=$' '
  shift 1
  eval "local a= ${*@Q}"

  core::createSavedFilePath suffix="${suffix}"
  local newFilePath="${REPLY}"
  printf '%s' "${content_nameRef}" >"${newFilePath}"
  if [[ ${silent} != "true" ]]; then
    log::printString "${newFilePath}"
  fi
  REPLY="${newFilePath}"
}

# ## log::printRaw
#
# Display something in the log stream.
# Does not check the log level.
#
# - $1: **content variable name** _as string_:
#       The variable name containing the content to print (can contain new lines).
#
# ```bash
# log::printRaw "my line"
# ```
# shellcheck disable=SC2317
function log::printRaw() {
  local -n rawStringToPrintInLog="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  # shellcheck disable=SC2034

  # evaluated the print statement built in log::init; it uses the local var rawStringToPrintInLog defined above
  eval "${GLOBAL_LOG_PRINT_STATEMENT_STANDARD}"
}

# ## log_setPrintfArgumentFromFormat (private)
#
# Set the variable printfArgument from the format specifier.
function log_setPrintfArgumentFromFormat() {
  local format="${printfFormat#'%'}"
  if [[ ${format} != *[0-9]* ]]; then
    printfArgument="\${${1}}"
  else
    format="${format%[sd]}"
    if [[ ${format} == "-"* ]]; then
      format="${format#-}"
      printfArgument="\${${1}:0:${format#-}}"
    else
      printfArgument="\${${1}:\${#${1}} - ${format} > 0 ? \${#${1}} - ${format} : 0}"
    fi
  fi
}

# ## log::parseLogPattern (private)
#
# Parse the log pattern and set variables that will be used to print the logs.
# If the pattern changes during runtime, the function `log::init` should be called again.
#
# - $1: **log pattern** _as string_:
#       The log pattern to parse.
#
# Available placeholders:
#
# - `<colorXXX>`: The value of the color variable `STYLE_COLOR_XXX`.
# - `<time>`: The current time formatted with the `format` string.
# - `<level>`: The log level.
# - `<levelColor>`: The color for the log level.
# - `<icon>`: The log level icon.
# - `<pid>`: The process ID of the bash instance that logged the message.
# - `<subshell>`: The subshell level of the bash instance that logged the message.
# - `<function>`: The name of the function that logged the message.
# - `<line>`: The line number where the message was logged.
# - `<source>`: The source of the function that logged the message.
# - `<varXXX>`: The value of an arbitrary variable `XXX`.
# - `<message>`: The log message (should be the last placeholder).
# - `<sourceFile>`: The file name of the source of the function that logged the message.
# - `<wrapPadding>`: The padding (spaces) used for wrapping the log message.
# - `<elapsedTime>`: The time elapsed since the start of the script.
# - `<elapsedTimeSinceLastLog>`: The time elapsed since the last log.
#
# Each placeholder can be fallowed by `{...}` to add the format specifier (see printf help).
#
# Returns:
#
# - ${REPLY}: The format string to use in a printf statement.
# - ${REPLY2}: The arguments (as a string space separated) to use in the printf statement.
# - ${REPLY3}: The length of the displayed log before the message.
# - ${REPLY4}: Extra code to compute variables that will be used to print the logs.
#
# ```bash
# log::parseLogPattern "<colorFaded><time>{(%H:%M:%S)T}<colorDefault> <levelColor><level> <icon><colorDefault> <message>"
# ```
# shellcheck disable=SC2120
function log::parseLogPattern() {
  local pattern="${1}"

  REPLY=""  # format
  REPLY2="" # arguments
  REPLY3=0  # wrap padding length
  REPLY4="" # code
  local -i wrapPaddingLength=0

  local normalString placeHolder formatSpecifier normalStringVisibleCharacters formatLengthTest printfFormat printfArgument
  while [[ -n ${pattern} ]]; do
    # extract the next placeholder
    if [[ ${pattern} =~ \<([^\>]+)\>(\{([^}]+)\})? ]]; then
      placeHolder="${BASH_REMATCH[1]}"
      formatSpecifier="${BASH_REMATCH[3]:-}"
      normalString="${pattern%%"${BASH_REMATCH[0]}"*}"
      pattern="${pattern#*"${BASH_REMATCH[0]}"}"
    else
      placeHolder=""
      normalString="${pattern}"
      pattern=""
    fi

    # handle the normal string
    if [[ -n ${normalString} ]]; then
      normalStringVisibleCharacters="${normalString}"
      string::removeTextFormatting normalStringVisibleCharacters
      REPLY+="%s"
      REPLY2+="\"${normalString//\"/\\\"}\" "
      wrapPaddingLength+=${#normalStringVisibleCharacters}

      if [[ ${normalString} == *$'\n'* ]]; then
        local stringAfterNewline="${normalString##*$'\n'}"
        wrapPaddingLength=${#stringAfterNewline}
      fi
    fi

    printfFormat=""

    # handle a placeholder
    case "${placeHolder}" in
    color*)
      placeHolder="${placeHolder#color}"
      local -n color="STYLE_COLOR_${placeHolder^^}"
      if [[ -n ${color:-} ]]; then
        printfFormat="%s"
        printfArgument="${color}"
      fi
      ;;
    time)
      printfFormat="%${formatSpecifier:-"(%H:%M:%S)T"}"
      printfArgument="\${EPOCHSECONDS}"
      ;;
    levelColor)
      if [[ ${VALET_CONFIG_ENABLE_COLORS:-} == "true" ]]; then
        printfFormat="%s"
        printfArgument="\${levelColor:-}"
      fi
      ;;
    level)
      printfFormat="%${formatSpecifier:-"-7s"}"
      log_setPrintfArgumentFromFormat "level"
      ;;
    icon)
      if [[ ${VALET_CONFIG_ENABLE_NERDFONT_ICONS:-} == "true" ]]; then
        printfFormat="%${formatSpecifier:-"-4s"}"
        printfArgument="\${icon:-}"
        # nerd font icons are 2 characters long
        wrapPaddingLength=$((wrapPaddingLength - 2))
      fi
      ;;
    var*)
      printfFormat="%${formatSpecifier:-"s"}"
      printfArgument="\${${placeHolder#var}:-}"
      REPLY4+=$'\n'"local variableToPrintInLog=\"\${${placeHolder#var}:-}\""
      log_setPrintfArgumentFromFormat "variableToPrintInLog"
      ;;
    pid)
      printfFormat="%${formatSpecifier:-"-5d"}"
      log_setPrintfArgumentFromFormat "BASHPID"
      ;;
    processName)
      printfFormat="%${formatSpecifier:-"-5d"}"
      # shellcheck disable=SC2034
      declare -g -A GLOBAL_PID_TO_PNAME
      REPLY4+=$'\n'"local processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]:-}; if [[ -z \${processName} ]]; then if [[ \${BASHPID} == \"${GLOBAL_PROGRAM_MAIN_PID}\" ]]; then GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"main\"; else string::numberToUniqueId \"\${BASHPID}\"; GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"\${REPLY}\"; fi; processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]}; fi"
      log_setPrintfArgumentFromFormat "processName"
      ;;
    subshell)
      printfFormat="%${formatSpecifier:-"-2d"}"
      log_setPrintfArgumentFromFormat "BASH_SUBSHELL"
      ;;
    function)
      printfFormat="%${formatSpecifier:-"-10s"}"
      REPLY4+=$'\n'"local functionName=\"\${FUNCNAME[1]:-}\""
      log_setPrintfArgumentFromFormat "functionName"
      ;;
    line)
      printfFormat="%${formatSpecifier:-"-4s"}"
      REPLY4+=$'\n'"local lineNumber=\"\${BASH_LINENO[1]:-0}\""
      log_setPrintfArgumentFromFormat "lineNumber"
      ;;
    source)
      printfFormat="%${formatSpecifier:-"-10s"}"
      REPLY4+=$'\n'"local sourcePath=\"\${BASH_SOURCE[1]:-shell}\""
      log_setPrintfArgumentFromFormat "sourcePath"
      ;;
    sourceFile)
      printfFormat="%${formatSpecifier:-"-10s"}"
      REPLY4+=$'\n'"local sourceFile=\"\${BASH_SOURCE[1]:-shell}\""
      REPLY4+=$'\n'"sourceFile=\"\${sourceFile##*/}\""
      log_setPrintfArgumentFromFormat "sourceFile"
      ;;
    elapsedTime)
      printfFormat="%${formatSpecifier:-"-7s"}"
      # shellcheck disable=SC1091
      source time
      REPLY4+=$'\n'"local REPLY; time::getProgramElapsedMicroseconds; time::getSecondsFromMicroseconds \"\${REPLY}\" precision=3; local loggedElapsedTime=\"\${REPLY}s\""
      log_setPrintfArgumentFromFormat "loggedElapsedTime"
      ;;
    elapsedTimeSinceLastLog)
      printfFormat="%${formatSpecifier:-"-7s"}"
      # shellcheck disable=SC1091
      source time
      REPLY4+=$'\n'"local REPLY; time::getProgramElapsedMicroseconds; local -i currentTime=\${REPLY}; _LOG_ELAPSED_TIME=\$(( currentTime - \${_LOG_ELAPSED_TIME:-0} )); time::getSecondsFromMicroseconds \"\${_LOG_ELAPSED_TIME}\" precision=3; local loggedElapsedTimeSinceLastLog=\"\${REPLY}s\"; _LOG_ELAPSED_TIME=\${currentTime}"
      log_setPrintfArgumentFromFormat "loggedElapsedTimeSinceLastLog"
      ;;
    wrapPadding)
      printfFormat="%s"
      printfArgument="\${GLOBAL_LOG_WRAP_PADDING}"
      ;;
    message)
      printfFormat="%s"
      printfArgument="\${messageToPrintInLog:-}"

      # shellcheck disable=SC2034
      REPLY3="${wrapPaddingLength}"
      ;;
    esac
    if [[ -z ${printfFormat} ]]; then
      continue
    fi
    REPLY+="${printfFormat}"
    REPLY2+="\"${printfArgument}\" "

    if [[ ${printfFormat} != "%s" ]]; then
      # shellcheck disable=SC2059
      printf -v formatLengthTest "${printfFormat}" "1"
      wrapPaddingLength+=${#formatLengthTest}
    fi
  done

  REPLY+="\n"
}

# ## log::init (private)
#
# In charge of setting up global variables that will be used to print the logs.
# We compute them once to avoid recomputing them at each log call.
# Indeed, each log function might have to output the same log to different file descriptors or files,
# we don't want to repeat code and we don't want to recompute the same output logic on each function.
#
# - ${logFileDescriptor} _as string_:
#       (optional) The variable name to use for the coproc.
#       (defaults to "${VALET_CONFIG_LOG_FD}" which defaults to 2).
# - ${logPattern} _as string_:
#       (optional) If defined, the log pattern to use.
#       (defaults to "")
#
# It uses the following config
#
# - ${VALET_CONFIG_LOG_PATTERN}: The pattern used to display a formatted log line.
# - ${VALET_CONFIG_LOG_FORMATTED_EXTRA_EVAL}: Contains a bash code executed before the print statement, to further process the variable messageToPrintInLog or define new variables to use in the log pattern.
#   to compute extra variables that can be used in the log pattern.
# - ${VALET_CONFIG_LOG_COLUMNS}: The number of columns to use for the log.
# - ${VALET_CONFIG_LOG_DISABLE_HIGHLIGHT}: true to disable highlight for ⌜⌝.
# - ${VALET_CONFIG_LOG_DISABLE_WRAP}: true if the log should not be wrapped.
# - ${VALET_CONFIG_LOG_FD}: The file descriptor to use for the log.
# - ${VALET_CONFIG_LOG_TO_DIRECTORY}: The directory in which to create an additional log file.
# - ${VALET_CONFIG_LOG_FILENAME_PATTERN}: pattern for the new log file name
# - ${VALET_CONFIG_ENABLE_NERDFONT_ICONS}: To know if we display a nerd icon for the log level.
#
# Returns:
#
# - ${GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG}: The statement to print the formatted log.
# - ${GLOBAL_LOG_PRINT_STATEMENT_STANDARD}: The statement to print the standard log.
# - ${GLOBAL_LOG_WRAP_PADDING}: The string with the number of spaces necessary to align with other log messages.
# - $[GLOBAL_LOG_COLUMNS}: The number of columns to use for the log.
# - $[GLOBAL_LOG_DISABLE_WRAP}: true if the log should not be wrapped.
# shellcheck disable=SC2120
function log::init() {
  local \
    logFileDescriptor="${VALET_CONFIG_LOG_FD:-}" \
    logPattern="${VALET_CONFIG_LOG_PATTERN:-"<colorFaded><time>{(%H:%M:%S)T}<colorDefault> <levelColor><level> <icon><colorDefault> <message>"}" \
    IFS=$' '
  eval "local a= ${*@Q}"

  GLOBAL_LOG_COLUMNS="${VALET_CONFIG_LOG_COLUMNS:-${GLOBAL_COLUMNS}}"
  GLOBAL_LOG_DISABLE_WRAP="${VALET_CONFIG_LOG_DISABLE_WRAP:-false}"

  if [[ -v GLOBAL_FD_LOG ]]; then
    # close if already opened
    exec {GLOBAL_FD_LOG}>&-
  fi

  # make sure the file descriptor (if any) is valid
  if [[ -n ${logFileDescriptor} && ${logFileDescriptor} != 2 ]]; then
    local isFdValid=false
    if [[ ${logFileDescriptor} =~ ^[0-9]+$ ]]; then
      if { : >&"${logFileDescriptor}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>&"${logFileDescriptor}"; then
        isFdValid=true
      fi
    elif { : >>"${logFileDescriptor}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>>"${logFileDescriptor}"; then
      # it is a file
      isFdValid=true
    fi
    if [[ ${isFdValid} != "true" ]]; then
      core::fail "The file descriptor for the logs VALET_CONFIG_LOG_FD is not valid: ⌜${logFileDescriptor}⌝."
    fi
    # we also redirect the builtin bash errors to the same FD so we can have them along the logs
    exec 2>&"${GLOBAL_FD_LOG}"
  else
    exec {GLOBAL_FD_LOG}>&"${GLOBAL_FD_ORIGINAL_STDERR}"
    exec 2>&"${GLOBAL_FD_ORIGINAL_STDERR}"
    logFileDescriptor="${GLOBAL_FD_ORIGINAL_STDERR}"
  fi

  local progressBarCode progressBarCode2 progressBarCode3 outputCode
  if [[ ${logFileDescriptor} =~ ^[0-9]+$ ]]; then
    # the fd is linked to the terminal
    outputCode="1>&${logFileDescriptor}"

    # clear the line before printing if we are display a progress bar/spinner
    if [[ -t ${logFileDescriptor} || ${GLOBAL_TEST_FORCE_FD_OPEN:-} == "true" ]]; then
      progressBarCode="local eraseLine; if [[ -v _PROGRESS_BAR_RUNNING ]]; then eraseLine=$'\e[2K'; fi"$'\n'
      progressBarCode2="\${eraseLine:-}"
      progressBarCode3=$'\n'"if [[ -v _PROGRESS_BAR_RUNNING ]]; then progress:redraw; fi"$'\n'
    fi
  else
    # it is a file
    outputCode="1>>\"${logFileDescriptor}\""
  fi

  # we prepare the variables that will be used to print the formatted logs
  local -n printfFormat=REPLY
  local -n printfArguments=REPLY2
  local -n wrapPaddingLength=REPLY3
  local -n beforePrintStatementCode=REPLY4
  log::parseLogPattern "${logPattern}"

  # string with the number of spaces necessary to align with other log messages
  if ((wrapPaddingLength > 0)); then
    printf -v GLOBAL_LOG_WRAP_PADDING "%${wrapPaddingLength}s" ""
  else
    GLOBAL_LOG_WRAP_PADDING=""
  fi

  # now we build the two statements that can be evaluated to print the logs
  # in the correct file descriptor or file (and to additional log file if needed)
  GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG=""
  GLOBAL_LOG_PRINT_STATEMENT_STANDARD=""

  if [[ ${VALET_CONFIG_ENABLE_COLORS:-} == "true" ]]; then
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="local -n levelColor=\"STYLE_COLOR_\${colorName}\""$'\n'
  fi
  if ((${#beforePrintStatementCode} > 0)); then
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="${beforePrintStatementCode}"$'\n'
  fi
  if [[ ${GLOBAL_LOG_DISABLE_WRAP} != "true" ]]; then
    # define REPLY/REPLY2 as local so we don't impact the parent scope (they are used during parsing)
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="local REPLY REPLY2"$'\n'"local -n messageToPrintInLog=REPLY"$'\n'"string::wrapWords messageToLog width=${GLOBAL_LOG_COLUMNS} newLinePadString=\"${GLOBAL_LOG_WRAP_PADDING}\" firstLineWidth=$((GLOBAL_LOG_COLUMNS - wrapPaddingLength))"$'\n'
  else
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="local -n messageToPrintInLog=messageToLog"$'\n'
  fi
  if [[ ${VALET_CONFIG_LOG_DISABLE_HIGHLIGHT:-false} != "true" ]]; then
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="messageToPrintInLog=\"\${messageToPrintInLog//⌜/${STYLE_COLOR_ACCENT}⌜}\""$'\n'"messageToPrintInLog=\"\${messageToPrintInLog//⌝/⌝${STYLE_COLOR_DEFAULT}}\""$'\n'
  fi
  if [[ -v VALET_CONFIG_LOG_FORMATTED_EXTRA_EVAL ]]; then
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+=$'\n'"${VALET_CONFIG_LOG_FORMATTED_EXTRA_EVAL}"$'\n'
  fi

  # define the formatted log statement
  local formattedLogStatement="printf \"${progressBarCode2:-}${printfFormat}\" ${printfArguments}"
  local standardStatement="printf \"${progressBarCode2:-}%s\" \"\${rawStringToPrintInLog:-}\""

  GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+="${progressBarCode:-}${formattedLogStatement} ${outputCode}${progressBarCode3:-}"
  GLOBAL_LOG_PRINT_STATEMENT_STANDARD+="${progressBarCode:-}${standardStatement} ${outputCode}${progressBarCode3:-}"

  # check if we need to additionally output the logs to a file
  if [[ -n ${VALET_CONFIG_LOG_TO_DIRECTORY:-} && ${VALET_CONFIG_LOG_TO_DIRECTORY:-} != "false" ]]; then
    # compute the name of the output file
    local logFile
    if [[ -n ${VALET_CONFIG_LOG_FILENAME_PATTERN:-} ]]; then
      eval "${VALET_CONFIG_LOG_FILENAME_PATTERN}"
      if [[ ! -v logFile ]]; then
        core::fail "The filename pattern for the log files VALET_CONFIG_LOG_FILENAME_PATTERN is not valid (does not create the variable logFile): ⌜${VALET_CONFIG_LOG_FILENAME_PATTERN}⌝."
      fi
    else
      printf -v logFile "log-%(%FT%H-%M-%S%z)T--PID_%06d.log" "${GLOBAL_MOCK_EPOCHSECONDS:-${EPOCHSECONDS}}" "${GLOBAL_MOCK_BASHPID:-${BASHPID}}"
    fi
    if [[ ${VALET_CONFIG_LOG_TO_DIRECTORY} == "true" ]]; then
      core::getUserStateDirectory
      VALET_CONFIG_LOG_TO_DIRECTORY="${REPLY}/logs"
    fi
    if [[ ! -d "${VALET_CONFIG_LOG_TO_DIRECTORY}" ]]; then
      command mkdir -p "${VALET_CONFIG_LOG_TO_DIRECTORY}" 1>/dev/null
    fi
    # append the log to the file
    GLOBAL_LOG_ADDITIONAL_LOG_FILE="${VALET_CONFIG_LOG_TO_DIRECTORY%/}/${logFile}"
    outputCode="1>>\"${GLOBAL_LOG_ADDITIONAL_LOG_FILE}\""
    GLOBAL_LOG_PRINT_STATEMENT_FORMATTED_LOG+=$'\n'"${formattedLogStatement} ${outputCode}"
    GLOBAL_LOG_PRINT_STATEMENT_STANDARD+=$'\n'"${standardStatement} ${outputCode}"
  fi

  # expose the current log pattern as a global variable
  # shellcheck disable=SC2034
  GLOBAL_LOG_PATTERN="${logPattern}"
}

# ## log::reload (private)
#
# If the log pattern or other related config variables are changed during runtime,
# this function can be called to recompute the variables used to print the logs.
function log::reload() {
  if [[ -v GLOBAL_LOG_COLUMNS ]]; then
    # log already initialized, we can reload it
    log::init "${@}"
  fi
}
