#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-terminal
source terminal

#===============================================================
# >>> Interactive prompts
#===============================================================

# ##  interactive::askForConfirmation
#
# Ask the user to press the button to continue.
#
# - $1: **prompt** _as string_:
#       the prompt to display
#
# Returns:
#
# - $?:
#   - 0 if the user pressed enter
#   - 1 otherwise
#
# ```bash
# interactive::askForConfirmation "Press enter to continue."
# ```
function interactive::askForConfirmation() {
  interactive::displayQuestion "${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  if ! interactive::askForConfirmationRaw; then
    return 1
  fi
  return 0
}

# ## interactive::askForConfirmationRaw
#
# Ask the user to press the button to continue.
#
# This raw version does not display the prompt or the answer.
#
# Returns:
#
# - $?:
#   - 0 if the user pressed enter
#   - 1 otherwise
#
# ```bash
# interactive::askForConfirmationRaw
# ```
function interactive::askForConfirmationRaw() {
  terminal::createSpace 2

  # print the current state (then move to column 1 to be ready to rewrite)
  printf ' %s%s%s' \
    "${ESC__CURSOR_HIDE}${STYLE_ACTIVE_BUTTON}" \
    "   (O)K   " \
    "${STYLE_RESET}${ESC__CURSOR_MOVE__}1${__ESC__COLUMN}" 1>&"${GLOBAL_FD_TUI}"

  local -i returnedCode=0
  while true; do
    # wait and handle key press
    if terminal::waitForChar -t 1; then
      case ${LAST_KEY_PRESSED} in
      $'\n' | ' ' | $'\r' | o | y)
        break
        ;;
      ESC)
        core::fail "Interactive session cancelled."
        ;;
      *)
        returnedCode=1
        break;
        ;;
      esac
    fi

    # break if fd 0 is closed or does not refer to a terminal.
    if [[ ! -t 0 ]]; then
      break;
    fi
  done

  printf '%s' "${ESC__ERASE_CHARS_RIGHT}${ESC__CURSOR_SHOW}" 1>&"${GLOBAL_FD_TUI}"

  return ${returnedCode}
}

# ## interactive::promptYesNo
#
# Ask the user to yes or no.
#
# - The user can switch between the two options with the arrow keys or space.
# - The user can validate the choice with the enter key.
# - The user can also validate immediately with the y or n key.
#
# Dialog boxes are displayed for the question and answer.
#
# - $1: **prompt** _as string_:
#       the prompt to display
# - $2: default _as bool_:
#       (optional) the default value to select
#       (defaults to true)
#
# Returns:
#
# - $?:
#   - 0 if the user answered yes
#   - 1 otherwise
# - ${RETURNED_VALUE}: true or false.
#
# ```bash
# if interactive::promptYesNo "Do you want to continue?"; then echo "Yes."; else echo "No."; fi
# ```
function interactive::promptYesNo() {
  interactive::displayQuestion "${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"

  if ! interactive::promptYesNoRaw "${2:-true}"; then
    interactive::displayAnswer "No."
    RETURNED_VALUE=false
    return 1
  fi

  interactive::displayAnswer "Yes."
  RETURNED_VALUE=true
  return 0
}

# ## interactive::promptYesNoRaw
#
# Ask the user to yes or no.
#
# - The user can switch between the two options with the arrow keys or space.
# - The user can validate the choice with the enter key.
# - The user can also validate immediately with the y or n key.
#
# This raw version does not display the prompt or the answer.
#
# - $1: default _as bool_:
#       (optional) the default value to select
#       (defaults to true)
#
# Returns:
#
# - $?:
#   - 0 if the user answered yes
#   - 1 otherwise
# - ${RETURNED_VALUE}: true or false.
#
# ```bash
# interactive::promptYesNoRaw "Do you want to continue?" && local answer="${RETURNED_VALUE}"
# ```
function interactive::promptYesNoRaw() {
  local state=${1:-true}

  terminal::createSpace 2

  printf '%s' "${ESC__CURSOR_HIDE}" 1>&"${GLOBAL_FD_TUI}"

  local yesColor noColor
  while true; do
    if [[ ${state} == "true" ]]; then
      yesColor="${STYLE_ACTIVE_BUTTON}"
      noColor="${STYLE_INACTIVE_BUTTON}"
    else
      yesColor="${STYLE_INACTIVE_BUTTON}"
      noColor="${STYLE_ACTIVE_BUTTON}"
    fi

    # print the current state (then move to column 1 to be ready to rewrite)
    printf ' %s%s%s   %s%s%s' \
      "${yesColor}" \
      "   (Y)ES   " \
      "${STYLE_RESET}" \
      "${noColor}" \
      "   (N)O   " \
      "${STYLE_RESET}${ESC__CURSOR_MOVE__}1${__ESC__COLUMN}" 1>&"${GLOBAL_FD_TUI}"

    # wait and handle key press
    if terminal::waitForChar -t 1; then
      case ${LAST_KEY_PRESSED} in
      $'\n' | ' ')
        break
        ;;
      y | Y)
        state=true
        break
        ;;
      n | N)
        state=false
        break
        ;;
      UP | LEFT | RIGHT | DOWN)
        if [[ ${state} == "true" ]]; then state=false; else state=true; fi
        ;;
      ESC)
        core::fail "Interactive session cancelled."
        ;;
      esac
    fi

    # break if fd 0 is closed or does not refer to a terminal.
    if [[ ! -t 0 ]]; then break; fi
  done

  printf '%s' "${ESC__ERASE_CHARS_RIGHT}${ESC__CURSOR_SHOW}" 1>&"${GLOBAL_FD_TUI}"

  if [[ ${state} == "true" ]]; then
    RETURNED_VALUE=${state}
    return 0
  fi

  RETURNED_VALUE=${state}
  return 1
}

# ## interactive::displayQuestion
#
# Displays a question to the user.
#
# The text is wrapped and put inside a box like so:
#
# ```text
#    ╭────────────────────────────────╮
# ░──┤ Is this an important question? │
#    ╰────────────────────────────────╯
# ```
#
# - $1: **prompt** _as string_:
#       the prompt to display
# - $2: max width _as int_:
#       (optional) the maximum width of text in the dialog box
#       (defaults to GLOBAL_COLUMNS)
#
# ```bash
# interactive::displayPrompt "Do you want to continue?"
# ```
function interactive::displayQuestion() {
  interactive::displayDialogBox "system" "${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" "${2:-}"
}

# ## interactive::displayAnswer
#
# Displays an answer to a previous question.
#
# The text is wrapped and put inside a box like so:
#
# ```text
#     ╭─────╮
#     │ No. ├──░
#     ╰─────╯
# ```
#
# - $1: **answer** _as string_:
#       the answer to display
# - $2: max width _as int_:
#       (optional) the maximum width of the text in the dialog box
#       (defaults to GLOBAL_COLUMNS)
#
# ```bash
# interactive::displayAnswer "My answer."
# ```
function interactive::displayAnswer() {
  interactive::displayDialogBox "user" "${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" "${2:-}"
}

# ## interactive::displayDialogBox
#
# Displays a dialog box with a speaker and a text.
#
# - $1: **speaker** _as string_:
#       the speaker (system or user)
# - $2: **text** _as string_:
#       the text to display
# - $3: max width _as int_:
#       (optional) the maximum width of the text in the dialog box
#       (defaults to GLOBAL_COLUMNS)
#
# ```bash
# interactive::displayDialogBox "system" "This is a system message."
# ```
function interactive::displayDialogBox() {
  local speaker="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local text="${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local requiredMaxTextWidth="${3:-${GLOBAL_COLUMNS}}"

  local -i maxTextWidth=$((GLOBAL_COLUMNS - 7))
  if (( requiredMaxTextWidth >= maxTextWidth )); then
    requiredMaxTextWidth=${maxTextWidth}
  fi
  local -i textWidth=${requiredMaxTextWidth}
  if (( ${#text} < textWidth )); then
    textWidth=${#text}
  fi

  string::wrapWords text "${textWidth}"
  local wrappedText="${RETURNED_VALUE}"

  local finalString line sideString
  local -i lineNumber=0 maxLineLength=0
  local IFS=$'\n'

  while read -r line; do
    if (( ${#line} > maxLineLength )); then
      maxLineLength=${#line}
    fi
  done <<<"${wrappedText}"
  textWidth=${maxLineLength}

  local frameBorder
  printf -v frameBorder "%${textWidth}s" " "
  frameBorder="${frameBorder// /─}"

  if [[ ${speaker} == "user" ]]; then

    local -i startColumn=$((GLOBAL_COLUMNS - textWidth - 7))
    startColumn=$((startColumn >= 0 ? startColumn : 0))
    startColumn=$((startColumn <= 8 ? startColumn : 8))
    startColumn+=1

    finalString+="${ESC__CURSOR_MOVE__}${startColumn}${__ESC__COLUMN}${STYLE_FRAMES}${SYMBOL_TL_CORNER}─${frameBorder}─${SYMBOL_TR_CORNER}${STYLE_RESET}"$'\n'
    while read -r line; do
      if (( lineNumber == 0 )); then
        sideString="├──░"
      else
        sideString="│"
      fi
      finalString+="${ESC__CURSOR_MOVE__}${startColumn}${__ESC__COLUMN}${STYLE_FRAMES}│${STYLE_RESET} ${line} ${ESC__CURSOR_MOVE__}$((textWidth + 3 + startColumn))${__ESC__COLUMN}${STYLE_FRAMES}${sideString}${STYLE_RESET}"$'\n'
      lineNumber+=1
    done <<<"${wrappedText}"
    finalString+="${ESC__CURSOR_MOVE__}${startColumn}${__ESC__COLUMN}${STYLE_FRAMES}${SYMBOL_BL_CORNER}─${frameBorder}─${SYMBOL_BR_CORNER}${STYLE_RESET}"$'\n'

  elif [[ ${speaker} == "system" ]]; then

    finalString+="   ${STYLE_FRAMES}${SYMBOL_TL_CORNER}─${frameBorder}─${SYMBOL_TR_CORNER}${STYLE_RESET}"$'\n'
    while read -r line; do
      if (( lineNumber == 0 )); then
        sideString="${STYLE_FRAMES}░──┤"
      else
        sideString="   ${STYLE_FRAMES}│"
      fi
      finalString+="${sideString}${STYLE_RESET} ${line} ${ESC__CURSOR_MOVE__}$((textWidth + 7))${__ESC__COLUMN}${STYLE_FRAMES}│${STYLE_RESET}"$'\n'
      lineNumber+=1
    done <<<"${wrappedText}"
    finalString+="   ${STYLE_FRAMES}${SYMBOL_BL_CORNER}─${frameBorder}─${SYMBOL_BR_CORNER}${STYLE_RESET}"$'\n'

  fi

  printf '%s' "${finalString}" 1>&"${GLOBAL_FD_TUI}"
}

