#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-fs
source fs

# ## system::getOs
#
# Returns the name of the current OS.
#
# Returns:
#
# - ${RETURNED_VALUE}: the name of the current OS: "darwin", "linux" or "windows".
#
# ```bash
# system::getOs
# local osName="${RETURNED_VALUE}"
# ```
function system::getOs() {
  local osName
  case "${OSTYPE:-}" in
    darwin*) osName="darwin";;
    linux*) osName="linux";;
    msys*) osName="windows";;
    *) osName="unknown";;
  esac
  RETURNED_VALUE="${osName}"
}

# ## system::getEnvVars
#
# Get the list of all the environment variables.
# In pure bash, no need for env or printenv.
#
# Returns:
#
# - ${RETURNED_ARRAY}: An array with the list of all the environment variables.
#
# ```bash
# system::getEnvVars
# for var in "${RETURNED_ARRAY[@]}"; do
#   printf '%s=%s\n' "${var}" "${!var}"
# done
# ```
#
# > This is faster than using mapfile on <(compgen -v).
function system::getEnvVars() {
  RETURNED_ARRAY=()
  for i in $(compgen -v); do
    RETURNED_ARRAY+=("${i}")
  done
}

# ## system::addToPath
#
# Add the given path to the PATH environment variable for various shells,
# by adding the appropriate export command to the appropriate file.
#
# Will also export the PATH variable in the current bash.
#
# - $1: **path** _as string_:
#       the path to add to the PATH environment variable.
#
# ```bash
# system::addToPath "/path/to/bin"
# ```
function system::addToPath() {
  local pathToAdd="${1:-}"

  log::debug "Adding directory ⌜${pathToAdd}⌝ to the PATH."

  fs::createDirectoryIfNeeded "${HOME}"

  local -i count=0
  local shellName
  for shellName in "bash" "ksh" "zsh" "tcsh" "csh" "xonsh" "fish" "nu"; do
    if ! command -v "${shellName}" &>/dev/null; then
      continue
    fi
    local configContent
    local configFile="${HOME}/.${shellName}rc"

    case ${shellName} in
    nu)
      configFile="${HOME}/.config/nushell/env.nu"
      fs::createDirectoryIfNeeded "${HOME}/.config/nushell"
      configContent="\$env.PATH = (\$env.PATH | split row (char esep) | append \"${pathToAdd}\")"
      ;;
    fish)
      # shellcheck disable=SC2088
      configFile="${HOME}/.config/fish/config.fish"
      fs::createDirectoryIfNeeded "${HOME}/.config/fish"
      configContent="fish_add_path '${pathToAdd}'"
      ;;
    tcsh | csh)
      configContent="set path = (\$path '${pathToAdd}')"
      ;;
    xonsh)
      configContent="\$PATH.append('${pathToAdd}')"
      ;;
    *)
      # shellcheck disable=SC2016
      printf -v configContent 'export PATH="%s:${PATH}"' "${pathToAdd}"
      ;;
    esac

    if [[ -f "${configFile}" ]] && fs::readFile "${configFile}" && [[ "${RETURNED_VALUE}" == *"${configContent}"* ]]; then
      log::info "The directory ⌜${pathToAdd}⌝ is already in the PATH for ⌜${shellName}⌝ shell."
      continue
    fi

    log::info "Adding directory ⌜${pathToAdd}⌝ to the PATH for ⌜${shellName}⌝ shell." \
      "Appending to ⌜${configFile}⌝:" \
      "${configContent}"

    printf '\n\n%s\n' "${configContent}" >> "${configFile}"
    count+=1
  done

  export PATH="${pathToAdd}:${PATH}"

  if (( count > 0 )); then
    log::warning "The directory ⌜${pathToAdd}⌝ has been added to the PATH for ${count} shells." \
      "Please login again to apply the changes on your current shell if you are not using bash."
  fi
}
