#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-fs
source fs
# shellcheck source=lib-string
source string

# ## yaml::parseFile
#
# Parses a YAML file and outputs a bash associative array with the content of the YAML
# accessible with dot notation.
#
# For example, if the YAML file contains:
#
# ```yaml
# key: test
# array:
#   - item1
#   - item2
# nested:
#   key: value
# ```
#
# The resulting associative array will have the following content:
#
# ```sh
# REPLY_MAP['key']="test"
# REPLY_MAP['array.length']=2
# REPLY_MAP['array[0]']="item1"
# REPLY_MAP['array[1]']="item2"
# REPLY_MAP['nested.key']="value"
# ```
#
# The length of each array is stored in the associative array with the key `(array).length` to allow
# iterating over the array items.
#
# - $1: **file path** _as string_:
#       The path to the YAML file to parse.
# - ${noFail} _as bool_:
#       (optional) A boolean to indicate wether or not the function should call core::fail (exit)
#       in case the parsing fails. By default, if the parsing fails, the script will exit.
#       (defaults to false)
# - ${prefixFirstDoc} _as bool_:
#       (optional) A boolean to indicate wether or not to prefix the keys of the first document
#       with "@[0]".
#       (defaults to false)
#
# Returns:
#
# - ${REPLY_MAP}: an associative array containing the content of the YAML file in dot notation.
# - ${REPLY_CODE}: (requires noFail=true)
#     - 0 if the file was parsed successfully,
#     - 1 if the file is not a valid YAML file.
# - ${REPLY}: (requires noFail=true) the errors encountered during the parsing if any.
#
# ```bash
# yaml::parseFile "file.yaml" noFail=true
# declare -p REPLY_MAP
# ```
#
# > /!\ this does not support all YAML features yet, working in progress...
# > TODO: complete the implementation to support more YAML features, and add more tests.
function yaml::parseFile() {
  local \
    path="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    noFail=false \
    prefixFirstDoc=false \
    IFS=" "
  shift 1
  eval "local a= ${*@Q}"

  REPLY_MAP=()
  REPLY_CODE=0
  REPLY=""

  # variables that carry over each loop iteration
  local isMultilineValue=false
  local -i arrayExtraIndentLevelResetValue=0

  # keyPaths keeps track of the current path in the YAML file.
  # keyIndentLevels keeps track of the indent level for each key.
  # arrayIndexes keeps track of the current array index for each key.
  # The length of all three arrays is equal to (the current indent level - 1).
  #
  # #                  | keyPaths                           |  keyIndentLevels  | arrayIndexes
  # # -----------------|------------------------------------|-------------------|---------------
  # nested:           # (nested)                            | (0)               | (-1)
  #   arr:            # (nested arr)                        | (0 2)             | (-1 -1)
  #   - key: thing    # (nested arr [0].key)                | (0 2 4)           | (-1 0 -1)
  #   arr2:           # (nested arr2)                       | (0 2)             | (-1 -1)
  #     - name: obj1  # (nested arr2 [0].name)              | (0 2 6)           | (-1 0 -1)
  #       array:      # (nested arr2 [0].array)             | (0 2 6)           | (-1 0 -1)
  #       - thing     # (nested arr2 [0].array [0])         | (0 2 6 8)         | (-1 0 0 -1)
  #       - arr:      # (nested arr2 [0].array [1].arr)     | (0 2 6 8)         | (-1 0 1 -1)
  #         - here    # (nested arr2 [0].array [1].arr [0]) | (0 2 6 8 10)      | (-1 0 1 0 -1)
  #     - name: obj2  # (nested arr2 [1].name)              | (0 2 6)           | (-1 1 -1)
  # thing: value      # (thing)                             | (0)               | (-1)
  local -a keyPaths=() keyIndentLevels=() arrayIndexes=()

  local line indent keyName fullKey value firstChar isArrayItemStart=false keyIndentLevelsFlatten \
    multilineTrimEnd=true multiLinesCumulatedLf multilineSeparator='' multilineFinalSeparator='' \
    errorPrefix="Error parsing YAML file ⌜${path}⌝" docPrefix=""
  local -i indentLevel=0 indentLevelIndex arrayIndex lineNumber=0 lastIndentLevel=0 arrayExtraIndentLevel \
    multiLineIndentLevel=-1 docNumber=0

  if [[ ${prefixFirstDoc} == "true" ]]; then
    docPrefix="@[0]."
  fi

  while IFS=$'\n' read -rd $'\n' line || [[ -n ${line:-} ]]; do
    lineNumber+=1
    # shellcheck disable=SC1001
    if [[ ${line} == [\#\%]* ]]; then
      continue
    fi

    line="${line%$'\r'}"
    IFS='.'

    # get indent, indent level and trim it from the line
    indent="${line%%[^[:space:]]*}"
    line="${line:${#indent}}"
    indent="${indent%%$'\t'*}"
    indentLevel=${#indent}

    # handle multiline continuation
    if [[ ${isMultilineValue} == "true" ]]; then
      if ((indentLevel > ${keyIndentLevels[-1]} - arrayExtraIndentLevel)); then
        if ((multiLineIndentLevel == 0)); then
          # the first line of a multiline value, determine the indent level of the multiline value
          multiLineIndentLevel=${indentLevel}
        fi

        if [[ ${multilineSeparator} == '$\n' ]]; then
          value+="${multiLinesCumulatedLf}"$'\n'
        else
          if [[ ${indentLevel} -gt ${multiLineIndentLevel} || -n ${multiLinesCumulatedLf} ]]; then
            if [[ -n ${value} ]]; then
              value+=$'\n'
            fi
            value+="${multiLinesCumulatedLf}"
          elif [[ -n ${value} ]]; then
            value+="${multilineSeparator}"
          fi
        fi
        value+="${indent:0:indentLevel-multiLineIndentLevel}${line}"
        multiLinesCumulatedLf=""
        continue
      elif [[ -z ${line// /} ]]; then
        multiLinesCumulatedLf+=$'\n'
        continue
      fi

      # end of a multiline value
      isMultilineValue=false
      multiLineIndentLevel=-1
      value+="${multilineFinalSeparator}"
      if [[ ${multilineTrimEnd} != "true" ]]; then
        value+="${multiLinesCumulatedLf}"
      fi
      REPLY_MAP["${fullKey}"]="${value}"
    fi

    # shellcheck disable=SC1001
    if [[ ${line} == [\#\%]* || ${#line} -eq 0 ]]; then
      # case of a command or an empty, non multiline, line
      continue
    fi

    # new doc
    if [[ ${line} == "---"* ]]; then
      docNumber+=1
      keyPaths=()
      keyIndentLevels=()
      arrayIndexes=()
      arrayExtraIndentLevelResetValue=0
      docPrefix="@[${docNumber}]."
      continue
    fi

    if [[ ${line} == "-"* ]]; then
      # case of an array
      line="${line:2}"
      indentLevel+=2
      arrayExtraIndentLevel=2
      isArrayItemStart=true
    else
      arrayExtraIndentLevel=${arrayExtraIndentLevelResetValue}
      arrayExtraIndentLevelResetValue=0
      isArrayItemStart=false
    fi

    # extract the key name and value, there can be only a value with no key name
    # in case of an array with a scalar
    firstChar="${line:0:1}"
    if [[ ${firstChar} == [\'\"] ]]; then
      keyName="${line:1}"
      keyName="${firstChar}${keyName%%"${firstChar}"*}${firstChar}"
      if [[ ${line:${#keyName}:1} != ":" ]]; then
        line="${keyName}"
        keyName=""
      else
        line="${line:${#keyName}}"
      fi
    elif [[ ${line} == *: ]]; then
      keyName="${line%%:*}"
      line="${line:${#keyName}}"
      # trim end spaces
      keyName="${keyName%"${keyName##*[^[:space:]]}"}"
    else
      keyName="${line%%: *}"
      # log::info "${line:${#keyName}:1} ${line@Q} at ${#keyName}"
      if [[ ${line:${#keyName}:1} != ":" ]]; then
        line="${keyName}"
        keyName=""
      else
        line="${line:${#keyName}}"
        # trim end spaces
        keyName="${keyName%"${keyName##*[^[:space:]]}"}"
      fi
    fi

    # unquote keyname and re quote it if needed
    if [[ ${keyName:0:1} == \" && ${keyName: -1} == \" ]]; then
      keyName="${keyName:1:-1}"
    elif [[ ${keyName:0:1} == \' && ${keyName: -1} == \' ]]; then
      keyName="${keyName:1:-1}"
    fi
    if [[ ${keyName} == *[![:word:]]* ]]; then
      keyName="\"${keyName}\""
    fi

    # remove comment and handle quoted values
    value="${line#:}"
    value="${value#"${value%%[^[:space:]]*}"}"
    if [[ ${value:0:1} == \' ]]; then
      value="${value:1}"
      value="${value//\'\'/$'\a'}"
      value="${value%%\'*}"
      value="${value//$'\a'/\'}"
    elif [[ ${value:0:1} == \" ]]; then
      value="${value:1}"
      value="${value//\\\"/$'\a'}"
      value="${value%%\"*}"
      value="${value//$'\a'/\"}"
      # in a double quoted value, we also want to convert \n, \t, \uXXXX... to their actual value
      eval "value=$'${value//\'/\\\'}'"
    else
      value="${value%% \#*}"
      if [[ ${value:0:1} == \# ]]; then
        value=""
      else
        # trim ending spaces
        value="${value%"${value##*[^[:space:]]}"}"
      fi
    fi

    log::debug "line: ${lineNumber}, key: ⌜${keyName}⌝, value: ⌜${value}⌝, line ⌜${line}⌝"

    if [[ ${isArrayItemStart} != "true" && -z ${keyName} && -z ${value} ]]; then
      # empty line
      continue
    fi

    # check for indent level. if valid, get the index of the indent level in the keyIndentLevels array
    if ((${#keyIndentLevels[@]} > 0)); then
      lastIndentLevel=${keyIndentLevels[-1]}
    fi
    if ((${#keyIndentLevels[@]} == 0 && indentLevel <= 4 + arrayExtraIndentLevel)); then
      indentLevelIndex=0
    elif ((indentLevel == lastIndentLevel)); then
      # case of a new key at the same level as the previous key
      indentLevelIndex=$((${#keyIndentLevels[@]} - 1))
    elif ((indentLevel > lastIndentLevel - arrayExtraIndentLevel)); then
      # case of a new key at a deeper level than the previous key
      if ((indentLevel > lastIndentLevel + 4 + arrayExtraIndentLevel)); then
        REPLY_CODE=1
        REPLY+="${errorPrefix} at line ${lineNumber}: too much indentation (expected at most $((lastIndentLevel + 4)))."
        if [[ ${noFail} != "true" ]]; then
          core::fail "${REPLY}"
        fi
        continue
      fi
      indentLevelIndex=${#keyIndentLevels[@]}
    else
      # case of a new key at a shallower level than the previous key
      # the current indent level must be in the keyIndentLevels array, otherwise it's an invalid YAML file
      keyIndentLevelsFlatten=".${keyIndentLevels[*]}."
      if [[ ${keyIndentLevelsFlatten} != *".${indentLevel}."* ]]; then
        REPLY_CODE=1
        IFS=","
        REPLY+="${errorPrefix} at line ${lineNumber}: invalid indentation (expected one of (${keyIndentLevels[*]}) but got ${indentLevel})."
        if [[ ${noFail} != "true" ]]; then
          core::fail "${REPLY}"
        fi
        continue
      fi
      keyIndentLevelsFlatten="${keyIndentLevelsFlatten%".${indentLevel}."*}"
      # indentLevelIndex will be the number of . left in keyIndentLevelsFlatten
      indentLevelIndex=${#keyIndentLevelsFlatten}
      keyIndentLevelsFlatten="${keyIndentLevelsFlatten//"."/}"
      indentLevelIndex=$((indentLevelIndex - ${#keyIndentLevelsFlatten}))
    fi

    # printf "%2s: indentLevel %2s indentLevelIndex %2s | %-20s | %-20s | %s\n" "${lineNumber}" "${indentLevel}" "${indentLevelIndex}" "${keyIndentLevels[*]}" "${keyName}" "${value}"

    # prepend the keyName with the current array index if we are in an array
    if [[ ${isArrayItemStart} == "true" ]]; then
      if ((${#keyIndentLevels[@]} == 0)); then
        # start of a "root" array
        keyPaths=("")
        keyIndentLevels=(0)
        arrayIndexes=(-1)
        indentLevelIndex=1
      fi
      arrayIndex=$((indentLevelIndex - 1))
      # increment current array index
      arrayIndexes[arrayIndex]=$((arrayIndexes[arrayIndex] + 1))

      # store the array length in the associative array with key (array).length
      fullKey="${keyPaths[*]:0:arrayIndex+1}.length"
      fullKey="${docPrefix}${fullKey#.}"
      fullKey="${fullKey//'.['/'['}"
      REPLY_MAP["${fullKey}"]="$((arrayIndexes[arrayIndex] + 1))"

      keyName="[${arrayIndexes[arrayIndex]}].${keyName}"
      keyName="${keyName%.}"

      while [[ ${line#"${line%%[^[:space:]]*}"} == "- "* ]]; do
        # case of an array within an array (e.g. `- - item1`)
        indent="${line%%"- "*}"
        keyPaths=("${keyPaths[@]:0:indentLevelIndex}" "${keyName}")
        arrayIndexes=("${arrayIndexes[@]:0:indentLevelIndex}" 0)
        keyIndentLevels=("${keyIndentLevels[@]:0:indentLevelIndex}" "${indentLevel}")
        indentLevel+=$((${#indent} + 2))
        indentLevelIndex+=1
        keyName="[0]"

        # store the array length in the associative array with key (array).length
        fullKey="${keyPaths[*]}.length"
        fullKey="${docPrefix}${fullKey#.}"
        fullKey="${fullKey//'.['/'['}"
        REPLY_MAP["${fullKey}"]="1"

        line="${line#"${indent}- "}"
        value="${value#"${value%%[^[:space:]]*}"}"
        value="${value#- }"
      done
    else
      arrayIndex=$((indentLevelIndex - 1))
      if ((arrayIndex >= 0 && arrayIndexes[arrayIndex] >= 0)); then
        # case of a new key inside an object inside an array
        keyName="[${arrayIndexes[arrayIndex]}].${keyName}"
        keyName="${keyName%.}"
      fi
    fi

    log::debug "line: ${lineNumber}, key: ⌜${keyName}⌝, value: ⌜${value}⌝, line ⌜${line}⌝"

    # determine what the current line represents
    if [[ ${value} == [\>\|]* ]]; then
      # new multiline value
      isMultilineValue=true
      multiLinesCumulatedLf=""
      if [[ ${value} == '|'* ]]; then
        multilineSeparator=$'\n'
      else
        multilineSeparator=' '
      fi
      value="${value:1}"
      if [[ ${value} == [0-4]* ]]; then
        multiLineIndentLevel=$((indentLevel - arrayExtraIndentLevel + ${value:0:1}))
        value="${value:1}"
      else
        multiLineIndentLevel=0
      fi
      if [[ ${value} == '-'* ]]; then
        multilineFinalSeparator=''
      else
        multilineFinalSeparator=$'\n'
      fi
      if [[ ${value} == '+'* ]]; then
        multilineTrimEnd=false
      else
        multilineTrimEnd=true
      fi
      value=""

    elif [[ ${line} == ': '* && (-n ${value} || ${line} == ': '[\"\'][\"\']*) ]]; then
      # a scalar value
      :

    elif [[ ${line} == ':'* && -z ${value} ]]; then
      # start of an object or array
      :

    elif [[ ${isArrayItemStart} == "true" && ${keyName} == *']' && -n ${value} ]]; then
      # case of a scalar array item with no key name
      :

    elif [[ ${isArrayItemStart} == "true" && ${keyName} == *']' ]]; then
      # case of the start of an array (line contains only "-")
      arrayExtraIndentLevelResetValue=2

    elif [[ -z ${keyName} && -n ${value} && ${#keyPaths[@]} -eq 0 ]]; then
      # a simple scalar value
      fullKey="${docPrefix%.}"
      REPLY_MAP["${fullKey:-"@[${docNumber}]"}"]="${value}"
      continue

    else
      # invalid line
      REPLY_CODE=1
      IFS=' '
      REPLY+="${errorPrefix} at line ${lineNumber}: not a valid YAML line. level: ${indentLevel}, line: ⌜${line}⌝, keyName: ⌜${keyName}⌝, value: ⌜${value}⌝, keyPaths: ⌜${keyPaths[*]}⌝, isArrayItemStart: ${isArrayItemStart}, arrayIndexes: ⌜${arrayIndexes[*]}⌝."
      if [[ ${noFail} != "true" ]]; then
        core::fail "${REPLY}"
      fi
      continue
    fi

    keyPaths=("${keyPaths[@]:0:indentLevelIndex}" "${keyName}")
    arrayIndexes=("${arrayIndexes[@]:0:indentLevelIndex}" -1)
    keyIndentLevels=("${keyIndentLevels[@]:0:indentLevelIndex}" "${indentLevel}")

    if log::isDebugEnabled; then
      printf "%2s: %50s | %20s | %s\n" "${lineNumber}" "${keyPaths[*]}" "${keyIndentLevels[*]}" "${arrayIndexes[*]}"
    fi

    fullKey="${keyPaths[*]}"
    fullKey="${docPrefix}${fullKey#.}"
    fullKey="${fullKey//'.['/'['}"
    if [[ -n ${value} ]]; then
      REPLY_MAP["${fullKey}"]="${value}"
    fi

  done <"${path}"

  # close a multiline value if we reached the end of the file
  if [[ ${isMultilineValue} == "true" ]]; then
    value+="${multilineFinalSeparator}"
    if [[ ${multilineTrimEnd} != "true" ]]; then
      value+="${multiLinesCumulatedLf}"
    fi
    # shellcheck disable=SC2034
    REPLY_MAP["${fullKey:-"@[${docNumber}]"}"]="${value}"
  fi

  # shellcheck disable=SC2034
  REPLY_MAP["@.length"]="${docNumber}"
}
