#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-fs
source fs
# shellcheck source=lib-string
source string

# ## yaml::parseFile
#
# Parses a YAML file and outputs a bash associative array with the content of the YAML
# accessible with dot notation.
#
# For example, if the YAML file contains:
#
# ```yaml
# key: test
# array:
#   - item1
#   - item2
# nested:
#   key: value
# ```
#
# The resulting associative array will have the following content:
#
# ```sh
# REPLY_MAP['$.length']="0"
# REPLY_MAP['key']="test"
# REPLY_MAP['array.length']=2
# REPLY_MAP['array[0]']="item1"
# REPLY_MAP['array[1]']="item2"
# REPLY_MAP['nested.key']="value"
# ```
#
# - The length of each array is stored in the associative array with the key `(array).length` to allow
#   iterating over the array items.
# - The number of documents in the YAML file is stored in the associative array with the key `@.length`.
# - If a key contains a dot or square brackets, it will be quoted in the resulting associative array.
#
# - $1: **file path** _as string_:
#       The path to the YAML file to parse.
# - ${noFail} _as bool_:
#       (optional) A boolean to indicate wether or not the function should call core::fail (exit)
#       in case the parsing fails. By default, if the parsing fails, the script will exit.
#       (defaults to false)
# - ${prefixFirstDoc} _as bool_:
#       (optional) A boolean to indicate wether or not to prefix the keys of the first document
#       with "@[0]".
#       (defaults to false)
#
# Returns:
#
# - ${REPLY_MAP}: an associative array containing the content of the YAML file in dot notation.
# - ${REPLY_CODE}: (requires noFail=true)
#     - 0 if the file was parsed successfully,
#     - 1 if the file is not a valid YAML file.
# - ${REPLY}: (requires noFail=true) the errors encountered during the parsing if any.
#
# ```bash
# yaml::parseFile "file.yaml" noFail=true
# declare -p REPLY_MAP
# ```
#
# > /!\ This does not support some uncommon YAML features yet such as:
# > - explicit keys (e.g. `? {myobject: key}`)
# > - extraction of tag definitions (e.g. %TAG !e! tag:example.com,2000:app/)
function yaml::parseFile() {
  local \
    path="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
    noFail=false \
    prefixFirstDoc=false \
    IFS=" "
  shift 1
  eval "local a= ${*@Q}"

  REPLY_MAP=()

  local replyCode=0 \
    errors=""

  # variables that carry over each loop iteration
  local isMultilineValue=false isQuoteOpen=false
  local -i arrayExtraIndentLevelResetValue=0

  # keyPaths keeps track of the current path in the YAML file.
  # keyIndentLevels keeps track of the indent level for each key.
  # arrayIndexes keeps track of the current array index for each key.
  # The length of all three arrays is equal to (the current indent level - 1).
  #
  # #                  | keyPaths                           |  keyIndentLevels  | arrayIndexes
  # # -----------------|------------------------------------|-------------------|---------------
  # nested:           # (nested)                            | (0)               | (-1)
  #   arr:            # (nested arr)                        | (0 2)             | (-1 -1)
  #   - key: thing    # (nested arr [0].key)                | (0 2 4)           | (-1 0 -1)
  #   arr2:           # (nested arr2)                       | (0 2)             | (-1 -1)
  #     - name: obj1  # (nested arr2 [0].name)              | (0 2 6)           | (-1 0 -1)
  #       array:      # (nested arr2 [0].array)             | (0 2 6)           | (-1 0 -1)
  #       - thing     # (nested arr2 [0].array [0])         | (0 2 6 8)         | (-1 0 0 -1)
  #       - arr:      # (nested arr2 [0].array [1].arr)     | (0 2 6 8)         | (-1 0 1 -1)
  #         - here    # (nested arr2 [0].array [1].arr [0]) | (0 2 6 8 10)      | (-1 0 1 0 -1)
  #     - name: obj2  # (nested arr2 [1].name)              | (0 2 6)           | (-1 1 -1)
  # thing: value      # (thing)                             | (0)               | (-1)
  local -a keyPaths=() keyIndentLevels=() arrayIndexes=()

  local line indent keyName fullKey value firstChar isArrayItemStart=false keyIndentLevelsFlatten \
    multilineTrimEnd=true multiLinesCumulatedLf multilineSeparator='' multilineFinalSeparator='' \
    isKeyWithoutValue=false \
    errorPrefix="Error parsing YAML file ⌜${path}⌝" docPrefix=""
  local -i indentLevel=0 indentLevelIndex arrayIndex lineNumber=0 lastIndentLevel=0 arrayExtraIndentLevel \
    multiLineIndentLevel=-1 docNumber=0

  if [[ ${prefixFirstDoc} == "true" ]]; then
    docPrefix="@[0]."
  fi

  while IFS=$'\n' read -rd $'\n' line || [[ -n ${line:-} ]]; do
    lineNumber+=1
    # shellcheck disable=SC1001
    if [[ ${line} == [\#\%]* ]]; then
      continue
    fi

    line="${line%$'\r'}"
    IFS='.'

    # get indent, indent level and trim it from the line
    indent="${line%%[^[:space:]]*}"
    line="${line:${#indent}}"
    indent="${indent%%$'\t'*}"
    indentLevel=${#indent}

    # handle multiline quoted values
    if [[ ${isQuoteOpen} == "true" ]]; then
      log::debug "line inside a quote: ${line@Q}, REPLY: ${REPLY@Q}"
      if [[ -z ${line// /} ]]; then
        multiLinesCumulatedLf+=$'\n'
        continue
      fi

      if [[ -n ${multiLinesCumulatedLf} ]]; then
        value+="${multiLinesCumulatedLf}"
      elif [[ -n ${value} ]]; then
        value+=' '
      fi
      multiLinesCumulatedLf=""

      line="${firstChar}${line}"
      yaml_extractFirstQuotedTextFromLine
      log::debug "line inside a quote: ${line@Q}, REPLY: ${REPLY@Q}"
      value+="${REPLY%"${REPLY##*[^[:space:]]}"}"
      if [[ ${line} == "${firstChar}"* ]]; then
        # the quote is closed
        log::debug "quote closed"
        isQuoteOpen=false

        REPLY_MAP["${fullKey}"]="${value}"
        isKeyWithoutValue=false
      fi
      continue
    fi

    # handle multiline continuation
    if [[ ${isMultilineValue} == "true" ]]; then
      if ((indentLevel > ${keyIndentLevels[-1]} - arrayExtraIndentLevel)); then
        if ((multiLineIndentLevel == 0)); then
          # the first line of a multiline value, determine the indent level of the multiline value
          multiLineIndentLevel=${indentLevel}
        fi

        if [[ ${multilineSeparator} == '$\n' ]]; then
          value+="${multiLinesCumulatedLf}"$'\n'
        else
          if [[ ${indentLevel} -gt ${multiLineIndentLevel} || -n ${multiLinesCumulatedLf} ]]; then
            if [[ -n ${value} ]]; then
              value+=$'\n'
            fi
            value+="${multiLinesCumulatedLf}"
          elif [[ -n ${value} ]]; then
            value+="${multilineSeparator}"
          fi
        fi
        value+="${indent:0:indentLevel-multiLineIndentLevel}${line}"
        multiLinesCumulatedLf=""
        continue
      elif [[ -z ${line// /} ]]; then
        multiLinesCumulatedLf+=$'\n'
        continue
      fi

      # end of a multiline value
      isMultilineValue=false
      multiLineIndentLevel=-1
      value+="${multilineFinalSeparator}"
      if [[ ${multilineTrimEnd} != "true" ]]; then
        value+="${multiLinesCumulatedLf}"
      fi
      REPLY_MAP["${fullKey}"]="${value}"
      isKeyWithoutValue=false
    fi

    # shellcheck disable=SC1001
    if [[ ${line} == [\#\%]* || ${#line} -eq 0 ]]; then
      # case of a command or an empty, non multiline, line
      continue
    fi

    # new doc
    if [[ ${line} == "---"* ]]; then
      if ((${#keyPaths[@]} > 0)); then
        docNumber+=1
      fi
      keyPaths=()
      keyIndentLevels=()
      arrayIndexes=()
      arrayExtraIndentLevelResetValue=0
      if [[ ${prefixFirstDoc} == "true" || ${docNumber} -gt 0 ]]; then
        docPrefix="@[${docNumber}]."
      fi
      line="${line#---}"
      line="${line#"${line%%[^[:space:]]*}"}"
    fi

    if [[ ${line} == "-"* ]]; then
      # case of an array
      line="${line:2}"
      indentLevel+=2
      arrayExtraIndentLevel=2
      isArrayItemStart=true
    else
      arrayExtraIndentLevel=${arrayExtraIndentLevelResetValue}
      arrayExtraIndentLevelResetValue=0
      isArrayItemStart=false
    fi

    # extract the key name and value, there can be only a value with no key name
    # in case of an array with a scalar
    isQuoteOpen=false
    firstChar="${line:0:1}"
    if [[ ${firstChar} == [\'\"] ]]; then
      yaml_extractFirstQuotedTextFromLine
      log::debug "line after extraction: ${line@Q}, REPLY: ${REPLY@Q}"
      if [[ ${line} == "${firstChar}"* ]]; then
        # the quote is closed
        log::debug "quote closed"
        isQuoteOpen=false
        line="${line:1}"
      else
        # unclosed quote
        log::debug "quote is not closed!"
        isQuoteOpen=true
      fi
    elif [[ ${line} == *": "* ]]; then
      REPLY="${line%%: *}"
      line="${line:${#REPLY}}"
    elif [[ ${line} == *: ]]; then
      REPLY="${line%:}"
      line=":"
    else
      REPLY="${line}"
      line=""
    fi
    log::debug "line after 1st round: ${line@Q}, REPLY: ${REPLY@Q}"

    # act on open quote or not
    if [[ ${isQuoteOpen} == "true" ]]; then
      keyName=""
      # trim end spaces
      value="${REPLY%"${REPLY##*[^[:space:]]}"}"
    else
      # trim end spaces
      keyName="${REPLY%"${REPLY##*[^[:space:]]}"}"

      if [[ ${line} == ":"* ]]; then
        # register keyname
        if [[ (${firstChar} == [\'\"] && -z ${keyName}) || ${keyName} == *[\.\[]* ]]; then
          # key was quoted and need to be re-quoted
          keyName="\"${keyName}\""
        elif [[ -z ${keyName} ]]; then
          yaml_addParsingError "bad indentation of a mapping entry ${line@Q} (contains a ': ' but no key name)"
        fi

        line="${line#:}"
        # trim beginning spaces
        line="${line#"${line%%[^[:space:]]*}"}"

        firstChar="${line:0:1}"
        if [[ ${firstChar} == [\'\"] ]]; then
          yaml_extractFirstQuotedTextFromLine
          log::debug "line after extraction of value: ${line@Q}, REPLY: ${REPLY@Q}"
          if [[ ${line} == "${firstChar}"* ]]; then
            # the quote is closed
            log::debug "quote closed"
            isQuoteOpen=false
            line="${line:1}"
          else
            # unclosed quote
            log::debug "quote is not closed!"
            isQuoteOpen=true
          fi
          value="${REPLY}"
        else
          value="${line}"
        fi
      else
        value="${keyName}"
        keyName=""
      fi

      # act on open quote or not
      if [[ ${isQuoteOpen} == "true" ]]; then
        # trim ending spaces
        value="${value%"${value##*[^[:space:]]}"}"
      else
        if [[ ${firstChar} == [\'\"] ]]; then
          # check that the remaining line after the ending quote is empty or a comment, otherwise it's a syntax error
          line="${line#"${line%%[^[:space:]]*}"}"
          if [[ -n ${line} && ${line} != \#* ]]; then
            yaml_addParsingError "syntax error for ${line@Q}"
          fi
        else
          # remove trailing comments and spaces
          if [[ ${value} == \#* ]]; then
            value=""
          else
            value="${value%% \#*}"
            # trim ending spaces
            value="${value%"${value##*[^[:space:]]}"}"
          fi
        fi

        log::debug "line: ${lineNumber}, key: ${keyName@Q}, value: ${value@Q}, line ${line@Q}"

        if [[ ${isArrayItemStart} != "true" && -z ${keyName} && -z ${value} ]]; then
          # empty line
          continue
        fi
      fi
    fi

    # check for indent level. if valid, get the index of the indent level in the keyIndentLevels array
    if ((${#keyIndentLevels[@]} > 0)); then
      lastIndentLevel=${keyIndentLevels[-1]}
    fi
    if ((${#keyIndentLevels[@]} == 0 && indentLevel <= 4 + arrayExtraIndentLevel)); then
      # case of a new key at the root level
      indentLevelIndex=0
    elif ((indentLevel == lastIndentLevel)); then
      # case of a new key at the same level as the previous key
      indentLevelIndex=$((${#keyIndentLevels[@]} - 1))
      if [[ ${isKeyWithoutValue} == "true" ]]; then
        # the previous key add a null value
        REPLY_MAP["${fullKey}"]="null"
        isKeyWithoutValue=false
      fi
    elif ((indentLevel > lastIndentLevel - arrayExtraIndentLevel)); then
      # case of a new key at a deeper level than the previous key
      if ((indentLevel > lastIndentLevel + 4 + arrayExtraIndentLevel)); then
        yaml_addParsingError "too much indentation (expected at most $((lastIndentLevel + 4)))."
        continue
      fi
      indentLevelIndex=${#keyIndentLevels[@]}
    else
      # case of a new key at a shallower level than the previous key
      # the current indent level must be in the keyIndentLevels array, otherwise it's an invalid YAML file
      keyIndentLevelsFlatten=".${keyIndentLevels[*]}."
      if [[ ${keyIndentLevelsFlatten} != *".${indentLevel}."* ]]; then
        yaml_addParsingError "invalid indentation (expected one of (${keyIndentLevels[*]}) but got ${indentLevel})."
        continue
      fi
      keyIndentLevelsFlatten="${keyIndentLevelsFlatten%".${indentLevel}."*}"
      # indentLevelIndex will be the number of . left in keyIndentLevelsFlatten
      indentLevelIndex=${#keyIndentLevelsFlatten}
      keyIndentLevelsFlatten="${keyIndentLevelsFlatten//"."/}"
      indentLevelIndex=$((indentLevelIndex - ${#keyIndentLevelsFlatten}))
      if [[ ${isKeyWithoutValue} == "true" ]]; then
        # the previous key add a null value
        REPLY_MAP["${fullKey}"]="null"
        isKeyWithoutValue=false
      fi
    fi

    if log::isDebugEnabled; then
      printf "%2s: indentLevel %2s indentLevelIndex %2s | %-20s | %-20s | %s\n" "${lineNumber}" "${indentLevel}" "${indentLevelIndex}" "${keyIndentLevels[*]}" "${keyName}" "${value}"
    fi

    # prepend the keyName with the current array index if we are in an array
    if [[ ${isArrayItemStart} == "true" ]]; then
      if ((${#keyIndentLevels[@]} == 0)); then
        # start of a "root" array
        keyPaths=("")
        keyIndentLevels=(0)
        arrayIndexes=(-1)
        indentLevelIndex=1
      fi
      arrayIndex=$((indentLevelIndex - 1))
      # increment current array index
      arrayIndexes[arrayIndex]=$((arrayIndexes[arrayIndex] + 1))

      # store the array length in the associative array with key (array).length
      fullKey="${keyPaths[*]:0:arrayIndex+1}.length"
      fullKey="${docPrefix}${fullKey#.}"
      fullKey="${fullKey//'.['/'['}"
      REPLY_MAP["${fullKey}"]="$((arrayIndexes[arrayIndex] + 1))"

      keyName="[${arrayIndexes[arrayIndex]}].${keyName}"
      keyName="${keyName%.}"

      log::debug "array start: keyName: ${keyName@Q}, keyPaths: ${keyPaths[*]@Q}, arrayIndexes: ${arrayIndexes[*]@Q}, indentLevelIndex: ${indentLevelIndex}, arrayIndex: ${arrayIndex}"

      if [[ ${firstChar} != [\'\"] ]]; then
        if [[ ${value} == *"-" ]]; then
          value+=" "
        fi

        while [[ ${value#"${value%%[^[:space:]]*}"} == "- "* ]]; do
          # case of an array within an array (e.g. `- - item1`)
          indent="${value%%"- "*}"
          keyPaths=("${keyPaths[@]:0:indentLevelIndex}" "${keyName}")
          arrayIndexes=("${arrayIndexes[@]:0:indentLevelIndex}" 0)
          keyIndentLevels=("${keyIndentLevels[@]:0:indentLevelIndex}" "${indentLevel}")
          indentLevel+=$((${#indent} + 2))
          indentLevelIndex+=1
          keyName="[0]"

          # store the array length in the associative array with key (array).length
          fullKey="${keyPaths[*]}.length"
          fullKey="${docPrefix}${fullKey#.}"
          fullKey="${fullKey//'.['/'['}"
          REPLY_MAP["${fullKey}"]="1"

          value="${value#"${indent}- "}"
          if [[ ${value} == *"-" ]]; then
            value+=" "
          fi

          log::debug "array within array: keyName: ${keyName@Q}, keyPaths: ${keyPaths[*]@Q}, arrayIndexes: ${arrayIndexes[*]@Q}, indentLevelIndex: ${indentLevelIndex}, arrayIndex: ${arrayIndex}"
        done
      fi
    else
      arrayIndex=$((indentLevelIndex - 1))
      log::debug "arrayIndex: ${arrayIndex}, arrayIndexes: ${arrayIndexes[*]@Q}, keyName: ${keyName@Q}"
      if ((arrayIndex >= 0 && arrayIndexes[arrayIndex] >= 0)); then
        # case of a new key inside an object inside an array
        keyName="[${arrayIndexes[arrayIndex]}].${keyName}"
        keyName="${keyName%.}"
      fi
      log::debug "keyName after arrayIndex: ${keyName@Q}"
    fi

    log::debug "value: ${value@Q}, keyName: ${keyName@Q}, isArrayItemStart: ${isArrayItemStart}, firstChar: ${firstChar@Q}"

    # determine what the current line represents
    if [[ ${isQuoteOpen} == "true" ]]; then
      # case of an unclosed quote, we will continue to read the next lines until we find the closing quote
      multiLinesCumulatedLf=""
      if [[ -z ${keyName} && ${#keyPaths[@]} -eq 0 ]]; then
        # the doc contains only a simple scalar value
        fullKey="${docPrefix%.}"
        fullKey="${fullKey:-"@[${docNumber}]"}"
        continue
      fi

    elif [[ ${value} == [\>\|]* ]]; then
      # new multiline value
      isMultilineValue=true
      multiLinesCumulatedLf=""
      if [[ ${value} == '|'* ]]; then
        multilineSeparator=$'\n'
      else
        multilineSeparator=' '
      fi
      value="${value:1}"
      if [[ ${value} == [0-4]* ]]; then
        multiLineIndentLevel=$((indentLevel - arrayExtraIndentLevel + ${value:0:1}))
        value="${value:1}"
      else
        multiLineIndentLevel=0
      fi
      if [[ ${value} == '-'* ]]; then
        multilineFinalSeparator=''
      else
        multilineFinalSeparator=$'\n'
      fi
      if [[ ${value} == '+'* ]]; then
        multilineTrimEnd=false
      else
        multilineTrimEnd=true
      fi
      value=""

    elif [[ -n ${keyName} && (-n ${value} || ${firstChar} == [\'\"]) ]]; then
      # a scalar value
      :

    elif [[ ${isArrayItemStart} == "true" && ${keyName} == *']' && -n ${value} ]]; then
      # case of a scalar array item with no key name
      :

    elif [[ ${isArrayItemStart} == "true" && ${keyName} == *']' ]]; then
      # case of the start of an array (line contains only "-")
      arrayExtraIndentLevelResetValue=2

    elif [[ -n ${keyName} && -z ${value} ]]; then
      # start of an object or array
      :

    elif [[ -z ${keyName} && -n ${value} && ${#keyPaths[@]} -eq 0 ]]; then
      # the doc contains only a simple scalar value
      fullKey="${docPrefix%.}"
      REPLY_MAP["${fullKey:-"@[${docNumber}]"}"]="${value}"
      continue

    elif [[ -z ${keyName} && ${isKeyWithoutValue} == "true" && -n ${value} ]]; then
      # case of a key without value followed by a scalar value on the next line
      :

    else
      # invalid line
      yaml_addParsingError "invalid line ${line@Q}, level ${indentLevel}, keyName: ${keyName@Q}, value: ${value@Q}, keyPaths: ${keyPaths[*]@Q}, isArrayItemStart: ${isArrayItemStart}, arrayIndexes: ${arrayIndexes[*]@Q}"
      continue
    fi

    if [[ -z ${keyName} && ${isKeyWithoutValue} == "true" ]]; then
      keyPaths=("${keyPaths[@]:0:indentLevelIndex}")
      arrayIndexes=("${arrayIndexes[@]:0:indentLevelIndex}")
      keyIndentLevels=("${keyIndentLevels[@]:0:indentLevelIndex}")
    else
      keyPaths=("${keyPaths[@]:0:indentLevelIndex}" "${keyName}")
      arrayIndexes=("${arrayIndexes[@]:0:indentLevelIndex}" -1)
      keyIndentLevels=("${keyIndentLevels[@]:0:indentLevelIndex}" "${indentLevel}")
    fi

    if log::isDebugEnabled; then
      printf "%2s: %50s | %20s | %s\n\n" "${lineNumber}" "${keyPaths[*]}" "${keyIndentLevels[*]}" "${arrayIndexes[*]}"
    fi

    fullKey="${keyPaths[*]}"
    fullKey="${docPrefix}${fullKey#.}"
    fullKey="${fullKey//'.['/'['}"
    if [[ -n ${value} || ${firstChar} == [\'\"] ]]; then
      REPLY_MAP["${fullKey}"]="${value}"
      isKeyWithoutValue=false
    else
      isKeyWithoutValue=true
    fi

  done <"${path}"

  # close a multiline value if we reached the end of the file
  if [[ ${isMultilineValue} == "true" ]]; then
    value+="${multilineFinalSeparator}"
    if [[ ${multilineTrimEnd} != "true" ]]; then
      value+="${multiLinesCumulatedLf}"
    fi
    # shellcheck disable=SC2034
    REPLY_MAP["${fullKey:-"@[${docNumber}]"}"]="${value}"
  elif [[ ${isKeyWithoutValue} == "true" ]]; then
    # the previous key add a null value
    REPLY_MAP["${fullKey:-"@[${docNumber}]"}"]="null"
  fi

  # shellcheck disable=SC2034
  REPLY_MAP["@.length"]="$((docNumber + 1))"

  REPLY_CODE=${replyCode}
  REPLY="${errors}"
}

function yaml_extractFirstQuotedTextFromLine() {
  if [[ ${line} == \'* ]]; then
    line="${line:1}"
    line="${line//\'\'/$'\a'}"
    REPLY="${line%%\'*}"
    REPLY="${REPLY//$'\a'/\'}"
    line="${line:${#REPLY}}"
  else
    line="${line:1}"
    line="${line//\\\"/$'\a'}"
    REPLY="${line%%\"*}"
    REPLY="${REPLY//$'\a'/\"}"
    line="${line:${#REPLY}}"
    # in a double quoted value, we also want to convert \n, \t, \uXXXX... to their actual value
    eval "REPLY=$'${REPLY//\'/\\\'}'"
  fi
}

function yaml_addParsingError() {
  replyCode=1
  errors+="${errorPrefix} at line ${lineNumber}: ${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}."
  if [[ ${noFail} != "true" ]]; then
    core::fail "${errors}"
  fi
}
