#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# sfzf stands for full screen fuzzy search.
# This script uses a lot of "private" variables (starting with _).

# shellcheck source=lib-ansi-codes
source ansi-codes
# shellcheck source=lib-tui
source tui
# shellcheck source=lib-exe
source exe
# shellcheck source=lib-array
source array

#===============================================================
# >>> Customization
#===============================================================

SFZF_LEFT_PANE_HELP_TEXT="↑/↓: Move | Enter: Select | Esc: Quit"
SFZF_RIGHT_PANE_HELP_TEXT="←/→: Scroll | Page up/down: Scroll+"

#===============================================================
# >>> Custom drawing functions
#===============================================================

# ## sfzf::show
#
# Displays a menu where the user can search and select an item.
# The menu is displayed in full screen.
# Each item can optionally have a description/details shown in a right panel.
# The user can search for an item by typing.
#
# - $1: **prompt** _as string_:
#       The prompt to display to the user (e.g. Please pick an item).
# - $2: **array name** _as string_:
#       The items to display (name of a global array).
# - $3: select callback function name _as string_:
#       (optional) The function to call when an item is selected
#       (defaults to empty, no callback)
#       this parameter can be left empty to hide the preview right pane;
#       otherwise the callback function should have the following signature:
#   - $1: the current item
#   - $2: the item number;
#   - $3: the current panel width;
#   - it should return the details of the item in the `RETURNED_VALUE` variable.
# - $4: preview title _as string_:
#       (optional) the title of the preview right pane (if any)
#       (defaults to empty)
#
# Returns:
#
# - ${RETURNED_VALUE}: The selected item value (or empty).
# - ${RETURNED_VALUE2}: The selected item index (from the original array).
#                      Or -1 if the user cancelled the selection
#
# ```bash
# declare -g -a SELECTION_ARRAY
# SELECTION_ARRAY=("blue" "red" "green" "yellow")
# sfzf::show "What's your favorite color?" SELECTION_ARRAY
# log::info "You selected: ⌜${RETURNED_VALUE}⌝ (index: ⌜${RETURNED_VALUE2}⌝)"
# ```
function sfzf::show() {
  local prompt="${1}"
  local itemsArrayName="${2}"
  SFZF_ITEM_SELECTED_CALLBACK="${3:-}"
  SFZF_RIGHT_PANE_TITLE="${4:-"Details"}"

  sfzfInitialize "${itemsArrayName}"

  # save the original traps so we can restore them later
  local originalTraps
  exe::captureOutput trap -p SIGWINCH EXIT SIGINT SIGQUIT
  originalTraps="${RETURNED_VALUE}"

  # we still need to export the terminal size but in addition, we need to sfzfDrawScreen.
  # Note: SIGWINCH does not interrupt a read command and wait for it to complete so we need
  # to set a timeout on read to allow this refresh.
  trap 'onResize;' SIGWINCH

  # still need to handle the exit, but we also need to reset the terminal when exiting.
  trap 'tui::switchBackFromFullScreen; main::onExitInternal;' EXIT

  # interrupting closes the interactive session
  trap 'SFZF_CLOSE_INTERACTIVE_SESSION=true;' SIGINT SIGQUIT

  tui::switchToFullScreen
  sfzfDrawScreen "${prompt}"

  # before starting to wait for inputs, we clear up the key pressed
  tui::clearKeyPressed

  # main loop
  while true; do
    if tui::waitForChar -t 0.05; then
      onKeyPressed "${LAST_KEY_PRESSED}"
    fi

    # break if fd 0 is closed or does not refer to a terminal.
    if [[ ! -t 0 || ${SFZF_CLOSE_INTERACTIVE_SESSION} == "true" ]]; then break; fi

    # redraw the screen if the terminal was resized
    if [[ ${GLOBAL_SCREEN_REDRAW_REQUIRED:-false} == "true" ]]; then
      sfzfDrawScreen "${prompt}"
    fi

    # recompute the right pane content if needed
    # only do it each 0.4s at maximum
    if [[ ${SFZF_RECOMPUTE_RIGHT_PANE_CONTENT} == "true" && $((${EPOCHREALTIME//./} - ${LAST_RECOMPUTE_RIGHT_PANE_CONTENT_TIME:-"-99999"})) -gt 400000 ]]; then
      LAST_RECOMPUTE_RIGHT_PANE_CONTENT_TIME="${EPOCHREALTIME//./}"
      computeRightPaneContent
      drawRightPane
      drawPrompt
    fi
  done

  # restore the initial traps
  eval "${originalTraps}"
  tui::switchBackFromFullScreen

  if ((SFZF_FINAL_SELECTION_INDEX >= 0)); then
    RETURNED_VALUE="${SFZF_ORIGINAL_ITEMS[${SFZF_FINAL_SELECTION_INDEX}]}"
  else
    RETURNED_VALUE=""
  fi
  RETURNED_VALUE2="${SFZF_FINAL_SELECTION_INDEX}"
}

# Initializes the state for sfzf menu.
function sfzfInitialize() {
  local itemsArrayName="${1}"

  # see if there is a preview panel of not
  if [[ -z ${SFZF_ITEM_SELECTED_CALLBACK} ]]; then
    SFZF_HAS_PREVIEW=false
  else
    SFZF_HAS_PREVIEW=true
  fi

  # an array of items that will be displayed in the left pane
  local -n originalItems="${itemsArrayName}"

  SFZF_ORIGINAL_ITEMS=("${originalItems[@]}")

  # the list of items filtered with the search string
  # and the correspondence between the currently displayed indexes with
  # the original items indexes
  SFZF_FILTERED_ITEMS=()
  SFZF_FILTERED_ITEMS_CORRESPONDENCES=()

  SFZF_FINAL_SELECTION_INDEX=-1
  SFZF_SELECTED_FILTERED_ITEM_INDEX=0

  # index of the first item displayed in the left pane
  SFZF_LEFT_PANE_START_INDEX=0

  # index of the first line displayed in the right pane
  SFZF_RIGHT_PANE_START_INDEX=0

  # contains the current search st+ring of the user
  SFZF_SEARCH_STRING=""
  SFZF_PROMPT=""

  # switched to true when the user wants to close the session
  SFZF_CLOSE_INTERACTIVE_SESSION=false

  # set up colors
  if [[ ${VALET_CONFIG_ENABLE_COLORS:-} == "true" ]]; then
    SFZF_COLOR_RESET_TEXT="${VALET_CONFIG_SFZF_RESET_TEXT:-"${AC__TEXT_RESET}"}"
    SFZF_COLOR_STATIC="${VALET_CONFIG_SFZF_STATIC:-"${AC__FG_BRIGHT_BLACK}"}"
    SFZF_COLOR_FOCUS="${VALET_CONFIG_SFZF_FOCUS:-"${AC__FG_MAGENTA}"}"
    SFZF_COLOR_FOCUS_RESET="${VALET_CONFIG_SFZF_FOCUS_RESET:-"${AC__FG_RESET}"}"
    SFZF_COLOR_LETTER_HIGHLIGHT="${VALET_CONFIG_SFZF_LETTER_HIGHLIGHT:-"${AC__TEXT_INVERSE}${AC__FG_MAGENTA}"}"
    SFZF_COLOR_LETTER_HIGHLIGHT_RESET="${VALET_CONFIG_SFZF_LETTER_HIGHLIGHT_RESET:-"${AC__TEXT_NO_INVERSE}${AC__FG_RESET}"}"
    SFZF_COLOR_SELECTED_ITEM="${VALET_CONFIG_SFZF_SELECTED_ITEM:-"${AC__BG_BLACK}"}"
    SFZF_COLOR_SELECTED_ITEM_RESET="${VALET_CONFIG_SFZF_SELECTED_ITEM_RESET:-"${AC__BG_RESET}"}"
    SFZF_COLOR_PROMPT_STRING="${VALET_CONFIG_SFZF_PROMPT_STRING:-"${AC__FG_CYAN}${AC__TEXT_BOLD}"}"
    SFZF_COLOR_PROMPT_STRING_RESET="${VALET_CONFIG_SFZF_PROMPT_STRING_RESET:-"${AC__TEXT_RESET}"}"
    SFZF_COLOR_COUNT="${VALET_CONFIG_SFZF_COUNT:-"${AC__FG_YELLOW}"}"
    SFZF_COLOR_COUNT_RESET="${VALET_CONFIG_SFZF_COUNT_RESET:-"${AC__TEXT_RESET}"}"
  else
    SFZF_COLOR_RESET_TEXT=""
    SFZF_COLOR_STATIC=""
    SFZF_COLOR_FOCUS=""
    SFZF_COLOR_FOCUS_RESET=""
    SFZF_COLOR_LETTER_HIGHLIGHT="${AC__TEXT_INVERSE}"
    SFZF_COLOR_LETTER_HIGHLIGHT_RESET="${AC__TEXT_NO_INVERSE}"
    SFZF_COLOR_SELECTED_ITEM=""
    SFZF_COLOR_SELECTED_ITEM_RESET=""
    SFZF_COLOR_PROMPT_STRING=""
    SFZF_COLOR_PROMPT_STRING_RESET=""
    SFZF_COLOR_COUNT=""
    SFZF_COLOR_COUNT_RESET=""
  fi
}

# Draw or redraw the whole screen (initially or after a terminal resize).
function sfzfDrawScreen() {
  local prompt="${1}"
  local toPrint="${AC__CURSOR_HIDE}${SFZF_COLOR_STATIC}"

  # clear the screen, move to the top left corner
  toPrint+="${AC__ERASE_SCREEN}${AC__CURSOR_MOVE__}1;1${__AC__TO}"

  # compute the width of the left/right panel
  if [[ ${SFZF_HAS_PREVIEW} == "true" ]]; then
    SFZF_RIGHT_PANE_WIDTH=$((GLOBAL_COLUMNS * 9 / 20))
    SFZF_LEFT_PANE_WIDTH=$((GLOBAL_COLUMNS - SFZF_RIGHT_PANE_WIDTH))
  else
    SFZF_RIGHT_PANE_WIDTH=0
    SFZF_LEFT_PANE_WIDTH=${GLOBAL_COLUMNS}
  fi

  # For the left and the right pane:
  # - compute the screen line at which to start to display the pane
  # - compute the number of content lines for the pane

  # 1. draw the prompt string
  string::wrapWords "${prompt}" "$((SFZF_LEFT_PANE_WIDTH - 1))"
  prompt="${RETURNED_VALUE}"
  SFZF_LEFT_PANE_FIRST_LINE=1
  local IFS line
  toPrint+="${SFZF_COLOR_PROMPT_STRING}"
  while IFS= read -r line; do
    toPrint+="${line}"$'\n'
    SFZF_LEFT_PANE_FIRST_LINE=$((SFZF_LEFT_PANE_FIRST_LINE + 1))
  done <<<"${prompt}"
  toPrint+="${SFZF_COLOR_PROMPT_STRING_RESET}${SFZF_COLOR_STATIC}"
  SFZF_RIGHT_PANE_FIRST_LINE=1

  # on the left side, we need to have space for the prompt, separator and help
  SFZF_LEFT_PANE_FIRST_CONTENT_LINE=$((SFZF_LEFT_PANE_FIRST_LINE + 2))
  SFZF_LEFT_PANE_LINES=$((GLOBAL_LINES - (SFZF_LEFT_PANE_FIRST_LINE - 1) - 3))
  SFZF_LEFT_PANE_LINES=$((SFZF_LEFT_PANE_LINES > 0 ? SFZF_LEFT_PANE_LINES : 1))
  # on the right side, we need space for the top and bottom of the pane
  SFZF_RIGHT_PANE_FIRST_CONTENT_LINE=$((SFZF_RIGHT_PANE_FIRST_LINE + 1))
  SFZF_RIGHT_PANE_LINES=$((GLOBAL_LINES - (SFZF_RIGHT_PANE_FIRST_LINE - 1) - 2))
  SFZF_RIGHT_PANE_LINES=$((SFZF_RIGHT_PANE_LINES > 0 ? SFZF_RIGHT_PANE_LINES : 1))
  SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES=$((SFZF_RIGHT_PANE_LINES - 1 - SFZF_RIGHT_PANE_START_INDEX))

  # 2. draw the left help text
  local leftHelpWidth=$((${#SFZF_LEFT_PANE_HELP_TEXT} + 2))
  local leftHelp=" ${SFZF_LEFT_PANE_HELP_TEXT} "
  if ((leftHelpWidth > SFZF_LEFT_PANE_WIDTH - 4)); then
    leftHelpWidth=0
    leftHelp=""
  fi
  toPrint+="${AC__CURSOR_MOVE__}${GLOBAL_LINES};1${__AC__TO}░─${leftHelp}─${AC__REPEAT__}$((SFZF_LEFT_PANE_WIDTH - leftHelpWidth - 4))${__AC__LAST_CHAR}"
  if [[ ${SFZF_HAS_PREVIEW} == "true" ]]; then
    toPrint+="─"
  else
    toPrint+="░"
  fi

  # 3. draw the separator of the left pane
  toPrint+="${AC__CURSOR_MOVE__}$((SFZF_LEFT_PANE_FIRST_LINE + 1));1${__AC__TO}░─${AC__REPEAT__}$((SFZF_LEFT_PANE_WIDTH - 3))${__AC__LAST_CHAR}"
  if [[ ${SFZF_HAS_PREVIEW} == "true" ]]; then
    toPrint+="─"
  else
    toPrint+="░"
  fi

  # 4. draw the static portion of the right pane
  if [[ ${SFZF_HAS_PREVIEW} == "true" ]]; then
    # first line with title
    local titleWidth=$((${#SFZF_RIGHT_PANE_TITLE} + 2))
    local title=" ${SFZF_RIGHT_PANE_TITLE} "
    # -10 to have the space to display the page counter 000/000
    if ((titleWidth > SFZF_RIGHT_PANE_WIDTH - 4 - 10)); then
      titleWidth=0
      title=""
    fi
    toPrint+="${AC__CURSOR_MOVE__}${SFZF_RIGHT_PANE_FIRST_LINE};$((SFZF_LEFT_PANE_WIDTH + 1))${__AC__TO}┌─${title}─${AC__REPEAT__}$((SFZF_RIGHT_PANE_WIDTH - titleWidth - 4))${__AC__LAST_CHAR}░"

    # last line with help
    local helpWidth=$((${#SFZF_RIGHT_PANE_HELP_TEXT} + 2))
    local help=" ${SFZF_RIGHT_PANE_HELP_TEXT} "
    if ((helpWidth > SFZF_RIGHT_PANE_WIDTH - 4)); then
      helpWidth=0
      help=""
    fi
    toPrint+="${AC__CURSOR_MOVE__}${GLOBAL_LINES};$((SFZF_LEFT_PANE_WIDTH + 1))${__AC__TO}┴─${AC__REPEAT__}$((SFZF_RIGHT_PANE_WIDTH - helpWidth - 4))${__AC__LAST_CHAR}${help}─░"

    # left border of the right pane
    for ((line = SFZF_RIGHT_PANE_FIRST_LINE + 1; line <= SFZF_RIGHT_PANE_FIRST_LINE + SFZF_RIGHT_PANE_LINES; line++)); do
      toPrint+="${AC__CURSOR_MOVE__}${line};$((SFZF_LEFT_PANE_WIDTH + 1))${__AC__TO}"
      if ((line == SFZF_LEFT_PANE_FIRST_LINE + 1)); then
        toPrint+="┤"
      else
        toPrint+="│"
      fi
    done
  fi

  printf '%s' "${toPrint}"

  # reset the fetched details because they are for a given width that might have changed
  # shellcheck disable=SC2086
  unset -v ${!SFZF_RIGHT_PANE_CONTENT_ARRAY*}
  SFZF_RECOMPUTE_RIGHT_PANE_CONTENT=${SFZF_HAS_PREVIEW}

  drawLeftPane
  drawRightPane

  # finish with the prompt line, we show the cursor again
  drawPrompt
}

# Draw the left pane content.
function drawLeftPane() {
  local IFS
  local toPrint="${AC__CURSOR_HIDE}${SFZF_COLOR_RESET_TEXT}"

  getCurrentInitialItemsIndex
  local initialOriginalIndex=${RETURNED_VALUE}
  local initialNbFilteredItems=${#SFZF_FILTERED_ITEMS[@]}

  # Compute filtered items
  if [[ -n ${SFZF_SEARCH_STRING} ]]; then
    array::fuzzyFilterSort "${SFZF_SEARCH_STRING}" SFZF_ORIGINAL_ITEMS "${SFZF_COLOR_LETTER_HIGHLIGHT}" "${SFZF_COLOR_LETTER_HIGHLIGHT_RESET}" "$((SFZF_LEFT_PANE_WIDTH - 4))"
    SFZF_FILTERED_ITEMS=("${RETURNED_ARRAY[@]}")
    SFZF_FILTERED_ITEMS_CORRESPONDENCES=("${RETURNED_ARRAY2[@]}")
  else
    # for each item longer than the left width, cut and add ellipsis
    SFZF_FILTERED_ITEMS=()
    local line
    for line in "${SFZF_ORIGINAL_ITEMS[@]}"; do
      if ((${#line} > SFZF_LEFT_PANE_WIDTH - 3)); then
        line="${line:0:SFZF_LEFT_PANE_WIDTH - 4}…"
      fi
      SFZF_FILTERED_ITEMS+=("${line}")
    done
    SFZF_FILTERED_ITEMS_CORRESPONDENCES=()
    for ((i = 0; i < ${#SFZF_ORIGINAL_ITEMS[@]}; i++)); do
      SFZF_FILTERED_ITEMS_CORRESPONDENCES+=("${i}")
    done
    initialOriginalIndex=-1
  fi

  # make sure to select an existing index regarding the newly filtered items +
  # make sure it is in the view
  changeSelectedItemIndex 0

  # if we are not pointing to the same original item, we need to
  # recompute the right pane content
  getCurrentInitialItemsIndex
  local newOriginalIndex=${RETURNED_VALUE}
  if [[ ${initialOriginalIndex} -ne ${newOriginalIndex} ]]; then
    SFZF_RECOMPUTE_RIGHT_PANE_CONTENT=${SFZF_HAS_PREVIEW}
  fi

  # draw the items count
  if ((${#SFZF_FILTERED_ITEMS[@]} != initialNbFilteredItems)); then
    local totalItemCount="${#SFZF_ORIGINAL_ITEMS[@]}"
    local itemCount="${#SFZF_FILTERED_ITEMS[@]}"
    if (( itemCount > SFZF_LEFT_PANE_LINES )); then
      itemCount="${SFZF_LEFT_PANE_LINES}"
    fi
    local itemsCounter
    printf -v itemsCounter " %s%0${#totalItemCount}i%s/%i%s " "${SFZF_COLOR_COUNT}" "${itemCount}" "${SFZF_COLOR_COUNT_RESET}${SFZF_COLOR_STATIC}" "${totalItemCount}" "${SFZF_COLOR_RESET_TEXT}"
    local itemCounterLength=$((3 + ${#totalItemCount} * 2))
    toPrint+="${AC__CURSOR_MOVE__}$((SFZF_LEFT_PANE_FIRST_LINE + 1));$((SFZF_LEFT_PANE_WIDTH - itemCounterLength))${__AC__TO}${itemsCounter}"
  fi

  # draw the items
  local itemPrefix
  local -i index line=${SFZF_LEFT_PANE_FIRST_CONTENT_LINE}
  local -i max=$((SFZF_LEFT_PANE_START_INDEX + SFZF_LEFT_PANE_LINES - 1))
  max=$((max > ${#SFZF_FILTERED_ITEMS[@]} - 1 ? ${#SFZF_FILTERED_ITEMS[@]} - 1 : max))
  for ((index = SFZF_LEFT_PANE_START_INDEX; index <= max; index++)); do
    if ((index == SFZF_SELECTED_FILTERED_ITEM_INDEX)); then
      itemPrefix="${SFZF_COLOR_SELECTED_ITEM}${SFZF_COLOR_FOCUS}${VALET_CONFIG_INTERACTIVE_SELECTED_ITEM_CHARACTER:-"◆"} ${SFZF_COLOR_FOCUS_RESET}"
    else
      itemPrefix="  "
    fi
    toPrint+="${AC__CURSOR_MOVE__}${line};${SFZF_LEFT_PANE_WIDTH}${__AC__TO}${AC__ERASE_CHARS_LEFT}"$'\r'"${itemPrefix}${SFZF_FILTERED_ITEMS[index]}${SFZF_COLOR_SELECTED_ITEM_RESET}"
    line+=1
  done

  # clear the remaining lines
  for ((line = SFZF_LEFT_PANE_FIRST_CONTENT_LINE + line - SFZF_LEFT_PANE_FIRST_CONTENT_LINE; line < SFZF_LEFT_PANE_FIRST_CONTENT_LINE + SFZF_LEFT_PANE_LINES; line++)); do
    toPrint+="${AC__CURSOR_MOVE__}${line};${SFZF_LEFT_PANE_WIDTH}${__AC__TO}${AC__ERASE_CHARS_LEFT}"
  done

  # reposition the cursor
  toPrint+="${AC__CURSOR_MOVE__}$((SFZF_LEFT_PANE_FIRST_LINE));$((3 + ${#SFZF_PROMPT}))${__AC__TO}${AC__CURSOR_SHOW}"

  printf '%s' "${toPrint}"
}

# Compute the array that should be displayed in the right pane.
# It is stored in the SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY variable.
function computeRightPaneContent() {
  SFZF_RECOMPUTE_RIGHT_PANE_CONTENT=false
  if [[ ${SFZF_HAS_PREVIEW} != "true" ]]; then
    # nothing to do
    return 0
  fi

  SFZF_RIGHT_PANE_START_INDEX=0

  getCurrentInitialItemsIndex
  local -i originalItemIndex=${RETURNED_VALUE}

  if ((originalItemIndex < 0)); then
    unset SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY
    return 0
  fi

  # if we already have a cached version of the details, we use it
  # otherwise, we built it
  if [[ ! -v "SFZF_RIGHT_PANE_CONTENT_ARRAY${originalItemIndex}" ]]; then
    declare -n array="SFZF_RIGHT_PANE_CONTENT_ARRAY${originalItemIndex}"

    local originalItem="${SFZF_ORIGINAL_ITEMS[${originalItemIndex}]}"
    "${SFZF_ITEM_SELECTED_CALLBACK}" "${originalItem}" "${originalItemIndex}" "$((SFZF_RIGHT_PANE_WIDTH - 3))"
    local content="${RETURNED_VALUE%$'\n'}"

    array=()
    local line IFS
    while IFS= read -r line; do
      array+=("${line}")
    done <<<"${content}"
  fi

  declare -g -n SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY="SFZF_RIGHT_PANE_CONTENT_ARRAY${originalItemIndex}"
}

# Draw the right pane content.
function drawRightPane() {
  if [[ ${SFZF_HAS_PREVIEW} != "true" ]]; then
    # nothing to do
    return 0
  fi
  local toPrint="${AC__CURSOR_HIDE}${SFZF_COLOR_RESET_TEXT}"

  # compute the number of lines for the right pane content
  local contentLength
  if [[ ! -v SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY || ${#SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[@]} -eq 0 ]]; then
    contentLength=0
  else
    contentLength=${#SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[@]}
  fi

  # display the page counter
  local itemsCounter
  local itemsCounterLength
  local itemCount
  if ((contentLength > 0)); then
    itemCount="$((${#SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[@]} - SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES - 1))"
  else
    itemCount=0
  fi
  if ((itemCount > 0)); then
    printf -v itemsCounter " %s%0${#itemCount}i%s/%i%s " "${SFZF_COLOR_COUNT}" "${SFZF_RIGHT_PANE_START_INDEX}" "${SFZF_COLOR_COUNT_RESET}${SFZF_COLOR_STATIC}" "${itemCount}" "${SFZF_COLOR_RESET_TEXT}"
    itemsCounterLength=$((3 + ${#itemCount} * 2))
  else
    itemsCounter="─────────"
    itemsCounterLength=9
  fi
  local -i repeat=$((9 - itemsCounterLength))
  repeat=$((repeat > 0 ? repeat : 0))
  toPrint+="${AC__CURSOR_MOVE__}${SFZF_RIGHT_PANE_FIRST_LINE};$((GLOBAL_COLUMNS - 9 - 2))${__AC__TO}${SFZF_COLOR_STATIC}─${AC__REPEAT__}${repeat}${__AC__LAST_CHAR}${itemsCounter}"

  # draw the lines
  local -i index line=${SFZF_RIGHT_PANE_FIRST_CONTENT_LINE}
  local -i max=$((SFZF_RIGHT_PANE_START_INDEX + SFZF_RIGHT_PANE_LINES - 1))
  max=$((max > contentLength - 1 ? contentLength - 1 : max))
  for ((index = SFZF_RIGHT_PANE_START_INDEX; index <= max; index++)); do
    toPrint+="${AC__CURSOR_MOVE__}${line};$((SFZF_LEFT_PANE_WIDTH + 2))${__AC__TO}${AC__ERASE_CHARS_RIGHT} ${SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[index]}"
    line+=1
  done

  # clear the remaining lines
  for ((line = SFZF_RIGHT_PANE_FIRST_CONTENT_LINE + line - SFZF_RIGHT_PANE_FIRST_CONTENT_LINE; line < SFZF_RIGHT_PANE_FIRST_CONTENT_LINE + SFZF_RIGHT_PANE_LINES; line++)); do
    toPrint+="${AC__CURSOR_MOVE__}${line};$((SFZF_LEFT_PANE_WIDTH + 2))${__AC__TO}${AC__ERASE_CHARS_RIGHT}"
  done

  # if there is no content, display a "Nothing to show" message on the center of the right pane
  if ((contentLength == 0)); then
    local loadingMessage="Nothing to show…"
    toPrint+="${AC__CURSOR_MOVE__}$((SFZF_RIGHT_PANE_FIRST_CONTENT_LINE + SFZF_RIGHT_PANE_LINES / 2));$((SFZF_LEFT_PANE_WIDTH + 2 + SFZF_RIGHT_PANE_WIDTH / 2 - ${#loadingMessage} / 2))${__AC__TO}${loadingMessage}"
  fi

  # reposition the cursor
  toPrint+="${AC__CURSOR_MOVE__}$((SFZF_LEFT_PANE_FIRST_LINE));$((3 + ${#SFZF_PROMPT}))${__AC__TO}${AC__CURSOR_SHOW}"

  printf '%s' "${toPrint}"
}

# Draw the prompt line
function drawPrompt() {
  # check if we need to shorten the prompt
  SFZF_PROMPT="${SFZF_SEARCH_STRING}"
  if ((${#SFZF_SEARCH_STRING} > SFZF_LEFT_PANE_WIDTH - 4)); then
    SFZF_PROMPT="…${SFZF_SEARCH_STRING:${#SFZF_SEARCH_STRING} - (SFZF_LEFT_PANE_WIDTH - 4) + 1}"
  else
    SFZF_PROMPT="${SFZF_SEARCH_STRING}"
  fi
  printf '%s' "${AC__CURSOR_HIDE}${AC__CURSOR_MOVE__}$((SFZF_LEFT_PANE_FIRST_LINE));$((SFZF_LEFT_PANE_WIDTH))${__AC__TO}${AC__ERASE_CHARS_LEFT}"$'\r'"${SFZF_COLOR_STATIC}${VALET_CONFIG_INTERACTIVE_SELECTED_ITEM_CHARACTER:-">"} ${SFZF_COLOR_RESET_TEXT}${SFZF_COLOR_FOCUS}${SFZF_PROMPT}${AC__CURSOR_SHOW}"
}

# Returns the index of the item in the original array (if any, or -1).
# It returns in the RETURNED_VALUE variable.
function getCurrentInitialItemsIndex() {
  if ((SFZF_SELECTED_FILTERED_ITEM_INDEX >= 0 && SFZF_SELECTED_FILTERED_ITEM_INDEX < ${#SFZF_FILTERED_ITEMS_CORRESPONDENCES[@]})); then
    RETURNED_VALUE=${SFZF_FILTERED_ITEMS_CORRESPONDENCES[${SFZF_SELECTED_FILTERED_ITEM_INDEX}]}
    return 0
  fi
  RETURNED_VALUE=-1
}

# Modifies the selected item index.
# Make it loop.
#
# $1: The delta to apply to the current index.
#
# Usage:
#   changeSelectedItemIndex 1
function changeSelectedItemIndex() {
  local delta="${1:-0}"

  # if we have no items, we do nothing
  if [[ ${#SFZF_FILTERED_ITEMS[@]} -eq 0 ]]; then
    SFZF_SELECTED_FILTERED_ITEM_INDEX=-1
    SFZF_RECOMPUTE_RIGHT_PANE_CONTENT=${SFZF_HAS_PREVIEW}
    return 0
  fi

  local -i newIndex

  # compute the new index
  # cycle through if it was already at the end/beginning
  if ((SFZF_SELECTED_FILTERED_ITEM_INDEX <= 0 && delta < 0)); then
    newIndex=$((${#SFZF_FILTERED_ITEMS[@]} - 1))
  elif ((SFZF_SELECTED_FILTERED_ITEM_INDEX >= ${#SFZF_FILTERED_ITEMS[@]} - 1 && delta > 0)); then
    newIndex=0
  else
    newIndex=$((SFZF_SELECTED_FILTERED_ITEM_INDEX + delta))
    if ((newIndex < 0)); then
      newIndex=0
    elif ((newIndex >= ${#SFZF_FILTERED_ITEMS[@]})); then
      newIndex=$((${#SFZF_FILTERED_ITEMS[@]} - 1))
    fi
  fi

  # now we need to adjust the start index if needed
  # to make sure that the new index is visible on the screen
  if ((newIndex < SFZF_LEFT_PANE_START_INDEX)); then
    SFZF_LEFT_PANE_START_INDEX=${newIndex}
  elif ((newIndex > SFZF_LEFT_PANE_START_INDEX + SFZF_LEFT_PANE_LINES - 1)); then
    SFZF_LEFT_PANE_START_INDEX=$((newIndex - SFZF_LEFT_PANE_LINES + 1))
  fi

  SFZF_SELECTED_FILTERED_ITEM_INDEX=${newIndex}

  # if we are not pointing to the same item, we need to
  # recompute the right pane content
  if ((delta != 0)); then
    SFZF_RECOMPUTE_RIGHT_PANE_CONTENT=${SFZF_HAS_PREVIEW}
  fi
}

# Modifies the right pane start index.
#
# $1: The delta to apply to the current index.
#
# Usage:
#   changeRightPaneStartIndex 1
function changeRightPaneStartIndex() {
  local delta="${1:-0}"
  local newIndex=$((SFZF_RIGHT_PANE_START_INDEX + delta))
  if ((newIndex < 0)); then
    newIndex=0
  elif [[ ! -v SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY ]]; then
    newIndex=0
  elif (( newIndex >= ${#SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[@]} - SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES )); then
    newIndex=$((${#SFZF_RIGHT_PANE_CONTENT_CURRENT_ARRAY[@]} - 1 - SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES))
  fi
  SFZF_RIGHT_PANE_START_INDEX=${newIndex}
}

# Called when a key is pressed.
function onKeyPressed() {
  case ${LAST_KEY_PRESSED} in
  ESC)
    SFZF_CLOSE_INTERACTIVE_SESSION=true
    return 0
    ;;
  $'\n')
    # if we selected index is within the range of the filtered items
    # we can return the corresponding index in the original items
    getCurrentInitialItemsIndex
    SFZF_FINAL_SELECTION_INDEX=${RETURNED_VALUE}
    SFZF_CLOSE_INTERACTIVE_SESSION=true
    return 0
    ;;
  PAGE_DOWN)
    changeRightPaneStartIndex "$((SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES - 1))"
    drawRightPane
    ;;
  PAGE_UP)
    changeRightPaneStartIndex "-$((SFZF_RIGHT_PANE_MAX_DISPLAYED_LINES - 1))"
    drawRightPane
    ;;
  HOME)
    changeRightPaneStartIndex -999999
    drawRightPane
    ;;
  END)
    changeRightPaneStartIndex 999999
    drawRightPane
    ;;
  RIGHT)
    changeRightPaneStartIndex 1
    drawRightPane
    ;;
  LEFT)
    changeRightPaneStartIndex -1
    drawRightPane
    ;;
  UP)
    changeSelectedItemIndex -1
    drawLeftPane
    ;;
  DOWN)
    changeSelectedItemIndex 1
    drawLeftPane
    ;;
  DEL)
    SFZF_SEARCH_STRING=""
    drawPrompt
    drawLeftPane
    ;;
  # filter any special key
  $'\e') ;;
  *)
    # Case of keys that are supposed to only affect the search string
    case ${LAST_KEY_PRESSED} in
    BACKSPACE)
      SFZF_SEARCH_STRING="${SFZF_SEARCH_STRING%?}"
      drawPrompt
      drawLeftPane
      ;;
    # normal key
    ?)
      SFZF_SEARCH_STRING+="${LAST_KEY_PRESSED}"
      drawPrompt
      drawLeftPane
      ;;
    esac
    ;;
  esac
}

# Called when the user resizes the terminal.
function onResize() {
  # export terminal size does not work if both 1 and 2 fd
  # are not the terminal. We need to temporarily redirect
  exec 2>&4 4>&-
  tui::getTerminalSize
  exec 4>&2 2>"${SFZF_TEMPORARY_ERROR_FILE}"
  GLOBAL_SCREEN_REDRAW_REQUIRED=true;
}
