#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# ## regex::getFirstGroup
#
# Matches a string against a regex and returns the first capture group of the matched string.
#
# - $1: **string** _as string_:
#       the string to match
# - $2: **regex** _as string_:
#       the regex
#
# Returns:
#
# - `RETURNED_VALUE`: the first capture group in the matched string.
#                     Empty if no match.
#
# ```bash
# regex::getFirstGroup "name: julien" "name:(.*)"
# echo "${RETURNED_VALUE}"
# ```
#
# > Regex wiki: https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions
function regex::getFirstGroup() {
  # Usage: regex "string" "regex"
  if [[ ${1} =~ ${2} ]]; then
    RETURNED_VALUE="${BASH_REMATCH[1]:-}"
  else
    # shellcheck disable=SC2034
    RETURNED_VALUE=""
  fi
}
