#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# shellcheck source=lib-fs
source fs

# ## data::serialize
#
# Serialize the variables given as arguments to a script that can be evaluated to restore the variables with the same values.
# (call data::deserialize to restore the variables from the script).
#
# - $1: **file** _as string_:
#       If an absolute file path (starting with /) is given, the script will be written to this file.
#       Otherwise, the script will be written to a file created in the user state directory with the given file name.
# - $@: **variable names** _as string_:
#       The variable names to serialize. At least one variable name must be given.
#
# Returns:
#
# - ${REPLY}: the path of the file containing the script to restore the variables.
#
# ```bash
# data::serialize my-variables VAR1 VAR2
# local scriptPath="${REPLY}"
# ```
function data::serialize() {
  local file="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  shift 1
  if ((${#@} == 0)); then
    core::fail "The function ⌜${FUNCNAME:-?}⌝ requires at least one variable name to serialize."
  fi

  local finalPath
  if [[ ${file} == /* ]]; then
    finalPath="${file}"
  else
    core::getUserStateDirectory
    finalPath="${REPLY}/${file}"
  fi
  fs::createFileIfNeeded "${finalPath}"

  if ! declare -p "${@}" 1>"${finalPath}" 2>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
    IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
    core::fail "Failed to serialize variables ⌜${*}⌝ to script ⌜${finalPath}⌝:"$'\n'"${REPLY}"
  fi

  REPLY="${finalPath}"
}

# ## data::deserialize
#
# Get a string to eval in order to restore the variables stored using data::serialize.
#
# - $1: **file** _as string_:
#       If an absolute file path (starting with /) is given, the variables will be restored from this file.
#       Otherwise, the variables will be restored from a file in the user state directory with the given file name.
#
# Returns:
#
# - ${REPLY}: a string to eval in order to restore the variables stored using data::serialize.
# - ${REPLY_CODE}:
#   - 0 if the file exists and was successfully sourced to restore the variables.
#   - 1 if the file does not exist
#
# ```bash
# data::deserialize my-variables
# eval "${REPLY}"
# ```
function data::deserialize() {
  local file="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
  local finalPath
  if [[ ${file} == /* ]]; then
    finalPath="${file}"
  else
    core::getUserStateDirectory
    finalPath="${REPLY}/${file}"
  fi

  if [[ ! -f ${finalPath} ]]; then
    log::debug "The script file ⌜${finalPath}⌝ to deserialize does not exist."
    REPLY_CODE=1
    REPLY=""
    return 0
  fi

  fs::readFile "${finalPath}"
  REPLY_CODE=0
}
