#!/usr/bin/env bash

function main() {
  test::title "✅ Testing styles library"

  export VALET_CONFIG_ENABLE_COLORS=true
  export VALET_CONFIG_ENABLE_NERDFONT_ICONS=true
  export VALET_CONFIG_STYLE_SQUARED_BOXES=false
  export VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES=false
  export VALET_CONFIG_DISABLE_ESC_CODES=false
  styles::init

  test::printVars VALET_CONFIG_ENABLE_COLORS VALET_CONFIG_ENABLE_NERDFONT_ICONS VALET_CONFIG_STYLE_SQUARED_BOXES VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES VALET_CONFIG_DISABLE_ESC_CODES ESC__TEXT_BOLD ESC__FG_BLACK ESC__CURSOR_MOVE__ DRAW_TL_CORNER STYLE_ICON_ERROR

  export VALET_CONFIG_ENABLE_COLORS=false
  export VALET_CONFIG_ENABLE_NERDFONT_ICONS=false
  export VALET_CONFIG_STYLE_SQUARED_BOXES=true
  export VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES=true
  export VALET_CONFIG_DISABLE_ESC_CODES=false
  styles::init

  test::printVars VALET_CONFIG_ENABLE_COLORS VALET_CONFIG_ENABLE_NERDFONT_ICONS VALET_CONFIG_STYLE_SQUARED_BOXES VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES VALET_CONFIG_DISABLE_ESC_CODES ESC__TEXT_BOLD ESC__FG_BLACK ESC__CURSOR_MOVE__ DRAW_TL_CORNER STYLE_ICON_ERROR

  export VALET_CONFIG_ENABLE_COLORS=false
  export VALET_CONFIG_ENABLE_NERDFONT_ICONS=false
  export VALET_CONFIG_STYLE_SQUARED_BOXES=true
  export VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES=true
  export VALET_CONFIG_DISABLE_ESC_CODES=true
  styles::init

  test::printVars VALET_CONFIG_ENABLE_COLORS VALET_CONFIG_ENABLE_NERDFONT_ICONS VALET_CONFIG_STYLE_SQUARED_BOXES VALET_CONFIG_DISABLE_TEXT_ATTRIBUTES VALET_CONFIG_DISABLE_ESC_CODES ESC__TEXT_BOLD ESC__FG_BLACK ESC__CURSOR_MOVE__ DRAW_TL_CORNER STYLE_ICON_ERROR
}

main
