#!/usr/bin/env bash
set -Eeu -o pipefail

# This script is executed in a Docker container

function main() {
  export VALET_CONFIG_LOG_PATTERN="<level>{-8s} <message>"
  export VALET_CONFIG_LOG_COLUMNS=9999
  export VALET_CONFIG_LOG_DISABLE_WRAP=true
  export VALET_CONFIG_LOG_DISABLE_HIGHLIGHT=true
  export VALET_CONFIG_ENABLE_COLORS=false

  echo "#!/usr/bin/env bash" >/home/me/chmod
  chmod +x /home/me/chmod
  export PATH="/home/me:${PATH}"

  echo "================================================"
  echo "valet self setup (with all default options)"
  echo "================================================"

  # setup with all default options (simulate pressing ENTER for all prompts)
  echo $'\n\n\n\n\n\n\n\n\n\n' | /home/me/valet/valet self setup

  echo
  echo "================================================"
  echo "> tail --lines=1 /home/me/.bashrc"
  tail --lines=1 /home/me/.bashrc

  echo "> ls /home/me/.valet.d/showcase.d"
  ls /home/me/.valet.d/showcase.d

  echo "> grep -E \"(VALET_CONFIG_ENABLE_COLORS|VALET_CONFIG_ENABLE_NERDFONT_ICONS)\" /home/me/.config/valet/config"
  grep -E "(VALET_CONFIG_ENABLE_COLORS|VALET_CONFIG_ENABLE_NERDFONT_ICONS)" /home/me/.config/valet/config

  echo
  echo "================================================"
  echo "valet self setup --unattended"
  echo "================================================"

  /home/me/valet/valet self setup --unattended

  echo
  echo "================================================"
  echo "valet self setup (with no to all prompts)"
  echo "================================================"

  rm -Rf /home/me/.valet.d/showcase.d

  # setup answering no to all prompts
  echo $'nnnnnnnnnnn' | /home/me/valet/valet self setup

  echo "================================================"
  echo "> ls /home/me/.valet.d"
  ls /home/me/.valet.d

  echo
  echo "================================================"
  echo "valet self setup (with yes to all prompts)"
  echo "================================================"

  mkdir -p /home/me/.local/bin
  export PATH="/home/me/.local/bin:${PATH}"

  # setup answering yes to all prompts
  echo $'yyyyyyyyyyy' | /home/me/valet/valet self setup

  echo
  echo "================================================"
  echo "> cat /home/me/.local/bin/valet"
  cat /home/me/.local/bin/valet

  echo
  echo "> grep -E \"(VALET_CONFIG_ENABLE_COLORS|VALET_CONFIG_ENABLE_NERDFONT_ICONS)\" /home/me/.config/valet/config"
  grep -E "(VALET_CONFIG_ENABLE_COLORS|VALET_CONFIG_ENABLE_NERDFONT_ICONS)" /home/me/.config/valet/config

  echo
  echo "================================================"
  echo "valet self setup --unattended --copy-showcase --create-shim --add-to-path --setup-for-windows --global-installation"
  echo "================================================"

  /home/me/valet/valet self setup --unattended --copy-showcase --create-shim --add-to-path --setup-for-windows --global-installation
}

main

echo "Self setup tests passed."
