#!/usr/bin/env bash
set -Eeu -o pipefail
: <<"COMMAND_YAML"
A content between tags
array:
  - item1
  - item2
  - item3
COMMAND_YAML

echo "Hello, World!"

# : <<"COMMAND_YAML"
# yep!
# COMMAND_YAML

: <<"COMMAND_YAML"
And another one!
COMMAND_YAML

echo "Nice?!"